# -*- coding: utf-8 -*-
"""math+scrape+kanji -xtraweek04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s8ymc7BGIa-9W24gLSDjQL9GPUZZQutY

Loop through function inputs
"""

import matplotlib.pyplot as plt

xmin = -10
xmax = 10
ymin = -10
ymax = 10

fig, ax = plt.subplots()
plt.axis([xmin,xmax,ymin,ymax]) # window size
plt.plot([xmin,xmax],[0,0],'b') # blue x axis
plt.plot([0,0],[ymin,ymax], 'b') # blue y axis

for x in range(10):
    y = 0.5*x + 1
    plt.plot([x],[y], 'ro')

plt.show()

"""Use an array as inputs"""

import matplotlib.pyplot as plt
import numpy as np

xmin = -10
xmax = 10
ymin = -10
ymax = 10
points = 2*(xmax-xmin)
x = np.linspace(xmin, xmax, points)

fig, ax = plt.subplots()
plt.axis([xmin,xmax,ymin,ymax]) # window size
plt.plot([xmin,xmax],[0,0],'b') # blue x axis
plt.plot([0,0],[ymin,ymax], 'b') # blue y axis

y = 2*x +1
plt.plot(x,y, 'pink')

plt.show()

"""More ways to customize a graph"""

import matplotlib.pyplot as plt
import numpy as np

xmin = -10
xmax = 10
ymin = -10
ymax = 10
points = 2*(xmax-xmin)
x = np.linspace(xmin, xmax, points)

fig, ax = plt.subplots()
plt.axis([xmin,xmax,ymin,ymax]) # window size
plt.plot([xmin,xmax],[0,0],'b') # blue x axis
plt.plot([0,0],[ymin,ymax], 'b') # blue y axis

ax.set_xlabel("x values")
ax.set_ylabel("y values")
ax.set_title("Some Graph")
ax.grid(True)

ax.set_xticks(np.arange(xmin, xmax, 1))
ax.set_yticks(np.arange(ymin, ymax, 1))

y = 2*x +1
plt.plot(x,y, label='y=2x+1')
plt.plot([4],[6], 'ro', label='point')
plt.plot(x,3*x, label='steeper line')
plt.legend()
plt.show()

"""scrape data from webpage, outputs into <- folder .csv which can be imported to excel."""

!python3 -m venv myenv
!source myenv/bin/activate
!pip install crawl4ai asyncio nest_asyncio pandas beautifulsoup4 pyOpenSSL==24.2.1
!playwright install chromium
!sudo add-apt-repository universe
!sudo apt-get install libenchant-2-dev gstreamer1.0-dev libwoff-dev libgtk-4-dev libgraphene-1.0-dev libwoff2dec-dev libgstgl-1.0-dev libgstcodecparsers-1.0-dev libavif-dev libenchant-2 libsecret-1-dev libhyphen-dev libmanette-0.2-dev
!sudo apt-get update
!sudo apt-get upgrade -y
import asyncio
from crawl4ai import AsyncWebCrawler
import nest_asyncio
import pandas as pd
from bs4 import BeautifulSoup

# Apply nest_asyncio to enable running async code within Jupyter
nest_asyncio.apply()

# Install the required browser for Playwright
# !playwright install


async def main():
    # Create an instance of AsyncWebCrawler
    async with AsyncWebCrawler() as crawler:
        # Run the crawler on a URL
        result = await crawler.arun(url="https://crawl4ai.com/")

        # Print the extracted content .content
        # print(result.markdown)

        # Parse the HTML content using BeautifulSoup
        soup = BeautifulSoup(result.html, 'html.parser')

        # Find all 'p' tags and extract their text
        data = []
        for p_tag in soup.find_all('p'):
            data.append({'text': p_tag.text})  # Store in a list of dictionaries

        # Create a Pandas DataFrame from the extracted data
        df = pd.DataFrame(data)

        # Export the DataFrame to a CSV file
        df.to_csv('extracted_text.csv', index=False)
        print("Data saved to extracted_text.csv")

# Run the async main function
asyncio.run(main())

"""kanji 2 pic

"""

!apt-get install fonts-noto-cjk
!fc-list | grep Noto
from PIL import Image, ImageDraw, ImageFont
import os
import matplotlib.font_manager as fm
import matplotlib as mpl
import math
#Kyōiku-kanji 1026-2136   Jōyō-Kanji
kanji_data = [
    {"kanji":"一",  "meaning": "One", "reading": "ichi, itsu, hito-tsu"},
    {"kanji":"二",  "meaning": "Two", "reading": "ni, ji, futa-tsu"},
    {"kanji":"三",  "meaning": "Three", "reading": "san, mit-tsu"},
    {"kanji":"四",  "meaning": "Four", "reading": "shi, yot-tsu, yon"},
    {"kanji":"五",  "meaning": "Five", "reading": "go, itsu-tsu"},
    {"kanji":"六",  "meaning": "Six", "reading": "roku, mut-tsu"},
    {"kanji":"七",  "meaning": "Seven", "reading": "shichi, nana-tsu"},
    {"kanji":"八",  "meaning": "Eight", "reading": "hachi, yat-tsu"},
    {"kanji":"九",  "meaning": "Nine", "reading": "ku, kyū, kokono-tsu"},
    {"kanji":"十",  "meaning": "Ten", "reading": "jū, tō"},
    {"kanji":"百",  "meaning": "Hundred", "reading": "hyaku, momo"},
    {"kanji":"千",  "meaning": "Thousand", "reading": "sen, chi"},
    {"kanji":"上",  "meaning": "Up Above", "reading": "jō, ue, kami, a-geru"},
    {"kanji":"下",  "meaning": "Down Below", "reading": "ka, ge, shita, sa-geru, kuda-saru"},
    {"kanji":"左",  "meaning": "Left", "reading": "sa, hidari"},
    {"kanji":"右",  "meaning": "Right", "reading": "u, yū, migi"},
    {"kanji":"中",  "meaning": "Middle Inside", "reading": "chū, jū, naka"},
    {"kanji":"大",  "meaning": "Big Large", "reading": "dai, tai, ō-kii"},
    {"kanji":"小",  "meaning": "Small", "reading": "shō, chi-sai, ko, o"},
    {"kanji":"月",  "meaning": "Month Moon", "reading": "gatsu, getsu, tsuki"},
    {"kanji":"日",  "meaning": "Day, Sun", "reading": "nichi, jitsu, hi, ka"},
    {"kanji":"年",  "meaning": "Year", "reading": "nen, toshi"},
    {"kanji":"早",  "meaning": "Early, Fast", "reading": "sō, satsu, haya-i"},
    {"kanji":"木",  "meaning": "Tree, Wood", "reading": "moku, boku, ki"},
    {"kanji":"林",  "meaning": "Grove, Forest", "reading": "rin, hayashi"},
    {"kanji":"山",  "meaning": "Mountain", "reading": "san, zan, yama"},
    {"kanji":"川",  "meaning": "River", "reading": "sen, kawa"},
    {"kanji":"土",  "meaning": "Earth, Soil", "reading": "do, to, tsuchi"},
    {"kanji":"空",  "meaning": "Sky, Empty", "reading": "kū, sora, a-ku, kara"},
    {"kanji":"田",  "meaning": "Rice Field", "reading": "den, ta, da"},
    {"kanji":"天",  "meaning": "Heaven", "reading": "ten, ame, ama"},
    {"kanji":"生",  "meaning": "Life, Raw", "reading": "sei, shō, i-kiru, u-mu, nama"},
    {"kanji":"花",  "meaning": "Flower", "reading": "ka, hana"},
    {"kanji":"草",  "meaning": "Grass", "reading": "sō, kusa"},
    {"kanji":"虫",  "meaning": "Insect", "reading": "chū, mushi"},
    {"kanji":"犬",  "meaning": "Dog", "reading": "ken, inu"},
    {"kanji":"人",  "meaning": "Person", "reading": "jin, nin, hito"},
    {"kanji":"名",  "meaning": "Name", "reading": "mei, myō, na"},
    {"kanji":"女",  "meaning": "Woman", "reading": "jo, nyo, on'na"},
    {"kanji":"男",  "meaning": "Man", "reading": "dan, nan, otoko"},
    {"kanji":"子",  "meaning": "Child", "reading": "shi, su, ko"},
    {"kanji":"目",  "meaning": "Eye", "reading": "moku, me"},
    {"kanji":"耳",  "meaning": "Ear", "reading": "ji, ni, mimi"},
    {"kanji":"口",  "meaning": "Mouth", "reading": "kō, kuchi"},
    {"kanji":"手",  "meaning": "Hand", "reading": "shu, te"},
    {"kanji":"足",  "meaning": "Foot", "reading": "soku, ashi"},
    {"kanji":"見",  "meaning": "See", "reading": "ken, gen, mi-ru"},
    {"kanji":"音",  "meaning": "Sound", "reading": "on, ne, oto"},
    {"kanji":"力",  "meaning": "Power", "reading": "riki, ryoku, chikara"},
    {"kanji":"気",  "meaning": "Spirit", "reading": "ki, ke, iki"},
    {"kanji":"円",  "meaning": "Yen Circle", "reading": "en, maru"},
    {"kanji":"入",  "meaning": "Enter", "reading": "nyū, hai-ru, i-ru"},
    {"kanji":"出",  "meaning": "Exit", "reading": "shutsu, de-ru"},
    {"kanji":"立",  "meaning": "Stand", "reading": "ritsu, ta-tsu"},
    {"kanji":"休",  "meaning": "Rest", "reading": "kyū, yasumu"},
    {"kanji":"先",  "meaning": "Previous Ahead", "reading": "sen, saki"},
    {"kanji":"夕",  "meaning": "Evening", "reading": "seki, yū"},
    {"kanji":"本",  "meaning": "Book Origin", "reading": "hon, moto"},
    {"kanji":"文",  "meaning": "Text Sentence", "reading": "bun, mon, fumi"},
    {"kanji":"字",  "meaning": "Character Letter", "reading": "ji, aza"},
    {"kanji":"学",  "meaning": "Study Learning", "reading": "gaku, mana-bu"},
    {"kanji":"校",  "meaning": "School", "reading": "kō"},
    {"kanji":"村",  "meaning": "Village", "reading": "son, mura"},
    {"kanji":"町",  "meaning": "Town", "reading": "chō, machi"},
    {"kanji":"森",  "meaning": "Forest", "reading": "shin, mori"},
    {"kanji":"正",  "meaning": "Correct Just", "reading": "sei, shō, tada-shii, masa"},
    {"kanji":"水",  "meaning": "Water", "reading": "sui, mizu"},
    {"kanji":"火",  "meaning": "Fire", "reading": "ka, hi"},
    {"kanji":"玉",  "meaning": "Jewel", "reading": "gyoku, tama"},
    {"kanji":"王",  "meaning": "King", "reading": "ō, kimi"},
    {"kanji":"石",  "meaning": "Stone", "reading": "seki, koku, ishi"},
    {"kanji":"竹",  "meaning": "Bamboo", "reading": "chiku, take"},
    {"kanji":"糸",  "meaning": "Thread", "reading": "shi, ito"},
    {"kanji":"貝",  "meaning": "Shell", "reading": "bai, kai"},
    {"kanji":"車",  "meaning": "Vehicle", "reading": "sha, kuruma"},
    {"kanji":"金",  "meaning": "Gold Money", "reading": "kin, kane, kana"},
    {"kanji":"雨",  "meaning": "Rain", "reading": "u, ame, ama"},
    {"kanji":"赤",  "meaning": "Red", "reading": "seki, aka"},
    {"kanji":"青",  "meaning": "Blue", "reading": "sei, shō, ao"},
    {"kanji":"白",  "meaning": "White", "reading": "haku, shiro, shira"},
    {"kanji":"数",  "meaning": "Number", "reading": "sū, kazu"},
    {"kanji":"多",  "meaning": "Many Much", "reading": "ta, oo-i"},
    {"kanji":"少",  "meaning": "Few Little", "reading": "shō, suku-nai, suko-shi"},
    {"kanji":"万",  "meaning": "Ten Thousand", "reading": "man, yorozu"},
    {"kanji":"半",  "meaning": "Half", "reading": "han, naka-ba"},
    {"kanji":"形",  "meaning": "Shape", "reading": "kei, gyō, katachi"},
    {"kanji":"太",  "meaning": "Thick", "reading": "ta, futo-i"},
    {"kanji":"細",  "meaning": "Thin", "reading": "sai, hoso-i"},
    {"kanji":"広",  "meaning": "Wide", "reading": "kō, hiro-i"},
    {"kanji":"長",  "meaning": "Long Leader", "reading": "chō, naga-i"},
    {"kanji":"点",  "meaning": "Point", "reading": "ten, bochi"},
    {"kanji":"丸",  "meaning": "Round", "reading": "gan, maru"},
    {"kanji":"交",  "meaning": "Cross", "reading": "kō, maji-waru"},
    {"kanji":"光",  "meaning": "Light", "reading": "kō, hikari"},
    {"kanji":"角",  "meaning": "Angle", "reading": "kaku, kado, tsuno, sumi"},
    {"kanji":"計",  "meaning": "Measure Plan", "reading": "kei, haka-ru"},
    {"kanji":"直",  "meaning": "Straight Direct", "reading": "choku, jiki, tada-chi, nao-su"},
    {"kanji":"線",  "meaning": "Line", "reading": "sen, suji"},
    {"kanji":"矢",  "meaning": "Arrow", "reading": "shi, ya"},
    {"kanji":"弱",  "meaning": "Weak", "reading": "jaku, yowa-i"},
    {"kanji":"強",  "meaning": "Strong", "reading": "kyō, tsuyo-i"},
    {"kanji":"高",  "meaning": "High Tall", "reading": "kō, taka-i"},
    {"kanji":"同",  "meaning": "Same", "reading": "dō, on-aji"},
    {"kanji":"親",  "meaning": "Parent", "reading": "shin, oya"},
    {"kanji":"母",  "meaning": "Mother", "reading": "bo, haha, kā"},
    {"kanji":"父",  "meaning": "Father", "reading": "fu, chichi, tō"},
    {"kanji":"姉",  "meaning": "Older Sister", "reading": "shi, ane"},
    {"kanji":"兄",  "meaning": "Older Brother", "reading": "kei, kyō, ani"},
    {"kanji":"弟",  "meaning": "Younger Brother", "reading": "tei, dai, otōto"},
    {"kanji":"妹",  "meaning": "Younger Sister", "reading": "mai, imōto"},
    {"kanji":"自",  "meaning": "Self", "reading": "ji, shi, mizuka-ra"},
    {"kanji":"友",  "meaning": "Friend", "reading": "yū, tomo"},
    {"kanji":"体",  "meaning": "Body", "reading": "tai, karada"},
    {"kanji":"毛",  "meaning": "Hair", "reading": "mō, ke"},
    {"kanji":"頭",  "meaning": "Head", "reading": "tō, atama"},
    {"kanji":"顔",  "meaning": "Face", "reading": "gan, kao"},
    {"kanji":"首",  "meaning": "Neck", "reading": "shu, kubi"},
    {"kanji":"心",  "meaning": "Heart", "reading": "shin, kokoro"},
    {"kanji":"時",  "meaning": "Time Hour", "reading": "ji, toki"},
    {"kanji":"曜",  "meaning": "Day of the Week", "reading": "yō"},
    {"kanji":"朝",  "meaning": "Morning", "reading": "chō, asa"},
    {"kanji":"昼",  "meaning": "Noon Daytime", "reading": "chū, hiru"},
    {"kanji":"夜",  "meaning": "Night", "reading": "ya, yoru"},
    {"kanji":"分",  "meaning": "Minute Understand", "reading": "fun, bun, wa-karu"},
    {"kanji":"週",  "meaning": "Week", "reading": "shū"},
    {"kanji":"春",  "meaning": "Spring", "reading": "shun, haru"},
    {"kanji":"夏",  "meaning": "Summer", "reading": "ka, natsu"},
    {"kanji":"秋",  "meaning": "Autumn", "reading": "shū, aki"},
    {"kanji":"冬",  "meaning": "Winter", "reading": "tō, fuyu"},
    {"kanji":"今",  "meaning": "Now", "reading": "kon, ima"},
    {"kanji":"新",  "meaning": "New", "reading": "shin, atara-shii"},
    {"kanji":"古",  "meaning": "Old", "reading": "ko, furu-i"},
    {"kanji":"間",  "meaning": "Space Interval", "reading": "kan, ken, ma, aida"},
    {"kanji":"方",  "meaning": "Direction", "reading": "hō, kata"},
    {"kanji":"北",  "meaning": "North", "reading": "hoku, kita"},
    {"kanji":"南",  "meaning": "South", "reading": "nan, minami"},
    {"kanji":"東",  "meaning": "East", "reading": "tō, higashi, azuma"},
    {"kanji":"西",  "meaning": "West", "reading": "sei, sai, nishi"},
    {"kanji":"遠",  "meaning": "Far", "reading": "en, tō-i"},
    {"kanji":"近",  "meaning": "Near", "reading": "kin, chika-i"},
    {"kanji":"前",  "meaning": "Before Front", "reading": "zen, mae"},
    {"kanji":"後",  "meaning": "After Back", "reading": "go, kō, nochi, ushi-ro, ato"},
    {"kanji":"内",  "meaning": "Inside", "reading": "nai, uchi"},
    {"kanji":"外",  "meaning": "Outside", "reading": "gai, ge, soto, hoka, hazu-su"},
    {"kanji":"場",  "meaning": "Place", "reading": "jō, ba"},
    {"kanji":"地",  "meaning": "Ground Earth", "reading": "chi, ji"},
    {"kanji":"国",  "meaning": "Country", "reading": "koku, kuni"},
    {"kanji":"園",  "meaning": "Garden", "reading": "en, sono"},
    {"kanji":"谷",  "meaning": "Valley", "reading": "koku, tani"},
    {"kanji":"野",  "meaning": "Field", "reading": "ya, no"},
    {"kanji":"原",  "meaning": "Plain", "reading": "gen, hara"},
    {"kanji":"里",  "meaning": "Village Home", "reading": "ri, sato"},
    {"kanji":"市",  "meaning": "City Market", "reading": "shi, ichi"},
    {"kanji":"京",  "meaning": "Capital", "reading": "kyō, kei, miyako"},
    {"kanji":"風",  "meaning": "Wind", "reading": "fū, kaze"},
    {"kanji":"雪",  "meaning": "Snow", "reading": "setsu, yuki"},
    {"kanji":"雲",  "meaning": "Cloud", "reading": "un, kumo"},
    {"kanji":"池",  "meaning": "Pond", "reading": "chi, ike"},
    {"kanji":"海",  "meaning": "Sea", "reading": "kai, umi"},
    {"kanji":"岩",  "meaning": "Rock", "reading": "gan, iwa"},
    {"kanji":"星",  "meaning": "Star", "reading": "sei, hoshi"},
    {"kanji":"室",  "meaning": "Room", "reading": "shitsu, muro"},
    {"kanji":"戸",  "meaning": "Door", "reading": "ko, to, be"},
    {"kanji":"家",  "meaning": "House", "reading": "ka, ke, ie"},
    {"kanji":"寺",  "meaning": "Temple", "reading": "ji, tera"},
    {"kanji":"通",  "meaning": "Pass Through", "reading": "tsū, tō-ru, kayo-u"},
    {"kanji":"門",  "meaning": "Gate", "reading": "mon, kado"},
    {"kanji":"道",  "meaning": "Street Road", "reading": "dō, michi"},
    {"kanji":"話",  "meaning": "Speak", "reading": "wa, hanashi, hana-su"},
    {"kanji":"言",  "meaning": "Say", "reading": "gen, gon, i-u, koto"},
    {"kanji":"答",  "meaning": "Answer", "reading": "tō, kota-eru"},
    {"kanji":"声",  "meaning": "Voice", "reading": "sei, koe"},
    {"kanji":"聞",  "meaning": "Hear", "reading": "bun, mon, ki-ku"},
    {"kanji":"語",  "meaning": "Language", "reading": "go, kata-ru"},
    {"kanji":"読",  "meaning": "Read", "reading": "doku, yo-mu"},
    {"kanji":"書",  "meaning": "Write", "reading": "sho, ka-ku"},
    {"kanji":"記",  "meaning": "Record", "reading": "ki, shiru-su"},
    {"kanji":"紙",  "meaning": "Paper", "reading": "shi, kami"},
    {"kanji":"画",  "meaning": "Picture", "reading": "ga, kaku"},
    {"kanji":"絵",  "meaning": "Drawing Painting", "reading": "kai, e"},
    {"kanji":"図",  "meaning": "Map", "reading": "zu, to, haka-ru"},
    {"kanji":"工",  "meaning": "Craft", "reading": "kō, ku"},
    {"kanji":"教",  "meaning": "Teach", "reading": "kyō, oshi-eru"},
    {"kanji":"晴",  "meaning": "Clear", "reading": "sei, hare"},
    {"kanji":"思",  "meaning": "Think", "reading": "shi, omo-u"},
    {"kanji":"考",  "meaning": "Consider", "reading": "kō, kanga-eru"},
    {"kanji":"知",  "meaning": "Know", "reading": "chi, shi-ru"},
    {"kanji":"才",  "meaning": "Ability", "reading": "sai, zai, wazukani, zae"},
    {"kanji":"理",  "meaning": "Reason", "reading": "ri, kotowari"},
    {"kanji":"算",  "meaning": "Calculate", "reading": "san"},
    {"kanji":"作",  "meaning": "Make", "reading": "saku, sa, tsuku-ru"},
    {"kanji":"元",  "meaning": "Origin", "reading": "gen, gan, moto"},
    {"kanji":"食",  "meaning": "Eat", "reading": "shoku, ta-beru, ku-u"},
    {"kanji":"肉",  "meaning": "Meat", "reading": "niku"},
    {"kanji":"馬",  "meaning": "Horse", "reading": "ba, uma, ma"},
    {"kanji":"牛",  "meaning": "Cow", "reading": "gyū, ushi"},
    {"kanji":"魚",  "meaning": "Fish", "reading": "gyo, uo, sakana"},
    {"kanji":"鳥",  "meaning": "Bird", "reading": "chō, tori"},
    {"kanji":"羽",  "meaning": "Feather", "reading": "u, ha, hane"},
    {"kanji":"鳴",  "meaning": "Chirp", "reading": "mei, na-ku"},
    {"kanji":"麦",  "meaning": "Wheat", "reading": "baku, mugi"},
    {"kanji":"米",  "meaning": "Rice", "reading": "bei, mai, kome"},
    {"kanji":"茶",  "meaning": "Tea", "reading": "cha, sa"},
    {"kanji":"色",  "meaning": "Color", "reading": "shoku, iro"},
    {"kanji":"黄",  "meaning": "Yellow", "reading": "ō, ki"},
    {"kanji":"黒",  "meaning": "Black", "reading": "koku, kuro"},
    {"kanji":"来",  "meaning": "Come", "reading": "rai, ku-ru"},
    {"kanji":"行",  "meaning": "Go", "reading": "kō, gyō, i-ku, yu-ku, okona-u"},
    {"kanji":"帰",  "meaning": "Return", "reading": "ki, kaer-u"},
    {"kanji":"歩",  "meaning": "Walk", "reading": "ho, aru-ku, ayu-mu"},
    {"kanji":"走",  "meaning": "Run", "reading": "sō, hashi-ru"},
    {"kanji":"止",  "meaning": "Stop", "reading": "shi, to-maru"},
    {"kanji":"活",  "meaning": "Active", "reading": "katsu"},
    {"kanji":"店",  "meaning": "Laden", "reading": "ten, mise"},
    {"kanji":"買",  "meaning": "kaufen", "reading": "bai, ka-u"},
    {"kanji":"売",  "meaning": "verkaufen", "reading": "bai, u-ru"},
    {"kanji":"午",  "meaning": "Mittag", "reading": "go, uma"},
    {"kanji":"汽",  "meaning": "Dampf", "reading": "ki"},
    {"kanji":"弓",  "meaning": "Bogen (Waffe)", "reading": "kyū, yumi"},
    {"kanji":"回",  "meaning": "mal", "reading": "kai"},
    {"kanji":"会",  "meaning": "treffen", "reading": "kai, e, a-u"},
    {"kanji":"組",  "meaning": "Gruppe", "reading": "so, kumi"},
    {"kanji":"船",  "meaning": "Schiff", "reading": "sen, fune"},
    {"kanji":"明",  "meaning": "hell", "reading": "mei, aka-rui"},
    {"kanji":"社",  "meaning": "Firma", "reading": "sha, yashiro"},
    {"kanji":"切",  "meaning": "schneiden", "reading": "setsu, ki-ru"},
    {"kanji":"電",  "meaning": "Elektrizität", "reading": "den"},
    {"kanji":"毎",  "meaning": "jeder", "reading": "mai"},
    {"kanji":"合",  "meaning": "anpassen", "reading": "gō, a-u"},
    {"kanji":"当",  "meaning": "dies; treffen", "reading": "tō, a-taru"},
    {"kanji":"台",  "meaning": "Ständer, Podium", "reading": "dai, tai"},
    {"kanji":"楽",  "meaning": "fröhlich, Musik", "reading": "gaku, raku, tano-shii"},
    {"kanji":"公",  "meaning": "öffentlich", "reading": "kō, ōyake"},
    {"kanji":"引",  "meaning": "ziehen", "reading": "in, hi-ku"},
    {"kanji":"科",  "meaning": "Abteilung", "reading": "ka"},
    {"kanji":"歌",  "meaning": "Lied, Gedicht", "reading": "ka, uta"},
    {"kanji":"刀",  "meaning": "Schwert", "reading": "tō, katana"},
    {"kanji":"番",  "meaning": "Nummer Wache", "reading": "ban"},
    {"kanji":"用",  "meaning": "benutzen", "reading": "yō, mochi-iru"},
    {"kanji":"何",  "meaning": "was", "reading": "kanani, nan"},

  {"kanji":"丁", "meaning":"Block, small street", "reading":"chō, tei, hinoto"},
  {"kanji":"世", "meaning":"World, generation", "reading":"sei, se, yo"},
  {"kanji":"両", "meaning":"Both", "reading":"ryō"},
  {"kanji":"主", "meaning":"Master, owner, head", "reading":"shu, nushi, omo"},
  {"kanji":"乗", "meaning":"To ride, to mount", "reading":"jō, no-ru"},
  {"kanji":"予", "meaning":"Beforehand", "reading":"yo, arakajime"},
  {"kanji":"事", "meaning":"Thing, matter, affair", "reading":"ji, koto"},
  {"kanji":"仕", "meaning":"To serve, to do (a job)", "reading":"shi, tsuka-eru"},
  {"kanji":"他", "meaning":"Other", "reading":"ta, hoka"},
  {"kanji":"代", "meaning":"Era, generation", "reading":"dai, tai, ka-waru, yo"},
  {"kanji":"住", "meaning":"To live, to reside", "reading":"jū, su-mu"},
  {"kanji":"使", "meaning":"To use", "reading":"shi, tsuka-u"},
  {"kanji":"係", "meaning":"Connection, duty", "reading":"kei, kakari, kaka-ru"},
  {"kanji":"倍", "meaning":"Double", "reading":"bai"},
  {"kanji":"全", "meaning":"Whole, all", "reading":"zen, matta-ku, sube-te"},
  {"kanji":"具", "meaning":"Tool, ingredient", "reading":"gu, sona-eru, tsubusa-ni"},
  {"kanji":"写", "meaning":"To copy, to photograph", "reading":"sha, utsu-su"},
  {"kanji":"列", "meaning":"Row, line", "reading":"retsu"},
  {"kanji":"助", "meaning":"To help", "reading":"jo, tasu-keru"},
  {"kanji":"勉", "meaning":"Effort, to strive", "reading":"ben, tsuto-meru"},
  {"kanji":"動", "meaning":"To move", "reading":"dō, ugo-ku"},
  {"kanji":"勝", "meaning":"Victory, win", "reading":"shō, ka-tsu"},
  {"kanji":"化", "meaning":"To transform", "reading":"ka, ba-keru"},
  {"kanji":"区", "meaning":"District", "reading":"ku"},
  {"kanji":"医", "meaning":"Doctor", "reading":"i, iya-su, i-suru"},
  {"kanji":"去", "meaning":"To leave", "reading":"kyo, ko, sa-ru"},
  {"kanji":"反", "meaning":"To oppose, to bend", "reading":"han, so-ru"},
  {"kanji":"取", "meaning":"To take", "reading":"shu, to-ru"},
  {"kanji":"受", "meaning":"To receive", "reading":"ju, u-keru"},
  {"kanji":"号", "meaning":"Number, signal", "reading":"gō, yobina, sake-bu"},
  {"kanji":"向", "meaning":"To face, to go toward", "reading":"kō, mu-kau"},
  {"kanji":"君", "meaning":"You, monarch", "reading":"kun, kimi"},
  {"kanji":"味", "meaning":"Taste", "reading":"mi, aji, aji-wau"},
  {"kanji":"命", "meaning":"Life, fate", "reading":"mei, inochi"},
  {"kanji":"和", "meaning":"Harmony, Japan", "reading":"wa, yawa-ragu, nago-yaka"},
  {"kanji":"品", "meaning":"Goods, article", "reading":"shina"},
  {"kanji":"員", "meaning":"Member", "reading":"in"},
  {"kanji":"商", "meaning":"Commerce, business", "reading":"shō"},
  {"kanji":"問", "meaning":"Question", "reading":"mon, to-u, ton"},
  {"kanji":"坂", "meaning":"Hill, slope", "reading":"han, saka"},
  {"kanji":"央", "meaning":"Center", "reading":"ō"},
  {"kanji":"始", "meaning":"To begin", "reading":"shi, haji-meru"},
  {"kanji":"委", "meaning":"To entrust", "reading":"i, yuda-neru"},
  {"kanji":"守", "meaning":"To protect", "reading":"shu, mamo-ru"},
  {"kanji":"安", "meaning":"Cheap, peaceful", "reading":"yasu-i"},
  {"kanji":"定", "meaning":"To decide", "reading":"tei, jō, sada-meru"},
  {"kanji":"実", "meaning":"Fruit, reality, truth", "reading":"jitsu, mi, mino-ru"},
  {"kanji":"客", "meaning":"Guest, customer", "reading":"kyaku"},
  {"kanji":"宮", "meaning":"Shinto shrine, prince/princess", "reading":"kyū, miya"},
  {"kanji":"宿", "meaning":"Inn, lodging", "reading":"shuku, yado, yado-ru"},
  {"kanji":"寒", "meaning":"Cold", "reading":"kan, samu-i"},
  {"kanji":"対", "meaning":"Opposite, against", "reading":"tai, aite, soro-i"},
  {"kanji":"局", "meaning":"Office, station", "reading":"kyoku, tsubone"},
  {"kanji":"屋", "meaning":"Roof, shop", "reading":"oku, ya"},
  {"kanji":"岸", "meaning":"Coast", "reading":"gan, kishi"},
  {"kanji":"島", "meaning":"Island", "reading":"tō, shima"},
  {"kanji":"州", "meaning":"State, province", "reading":"shū, su"},
  {"kanji":"帳", "meaning":"Account book, curtain", "reading":"chō, tobari"},
  {"kanji":"平", "meaning":"Flat, level", "reading":"hei, byō, tai-ra, hira"},
  {"kanji":"幸", "meaning":"Happiness, fortune", "reading":"kō, saiwa-i, shiawa-se"},
  {"kanji":"度", "meaning":"Degree, measure", "reading":"do, tabi"},
  {"kanji":"庫", "meaning":"Warehouse, storehouse", "reading":"ko, ku, kura"},
  {"kanji":"庭", "meaning":"Garden, courtyard", "reading":"tei, niwa"},
  {"kanji":"式", "meaning":"Style, ceremony", "reading":"shiki"},
  {"kanji":"役", "meaning":"Role, service", "reading":"yaku"},
  {"kanji":"待", "meaning":"To wait", "reading":"tai, ma-tsu"},
  {"kanji":"急", "meaning":"Urgent, to hurry", "reading":"kyū, iso-gu"},
  {"kanji":"息", "meaning":"Breath", "reading":"soku, iki"},
  {"kanji":"悪", "meaning":"Bad", "reading":"aku, waru-i"},
  {"kanji":"悲", "meaning":"Sad", "reading":"hi, kana-shii"},
  {"kanji":"想", "meaning":"To think, to imagine", "reading":"sō"},
  {"kanji":"意", "meaning":"Idea, thought", "reading":"i"},
  {"kanji":"感", "meaning":"Feeling, sense", "reading":"kan"},
  {"kanji":"所", "meaning":"Place", "reading":"sho, tokoro"},
  {"kanji":"打", "meaning":"To strike, to hit", "reading":"da, u-tsu"},
  {"kanji":"投", "meaning":"To throw", "reading":"tō, na-geru"},
  {"kanji":"拾", "meaning":"To pick up", "reading":"hiro-u"},
  {"kanji":"持", "meaning":"To hold", "reading":"ji, mo-tsu"},
  {"kanji":"指", "meaning":"Finger", "reading":"shi, yubi, sa-su"},
  {"kanji":"放", "meaning":"To release", "reading":"hō, hana-su"},
  {"kanji":"整", "meaning":"To organize, to prepare", "reading":"sei, totono-eru"},
  {"kanji":"旅", "meaning":"Journey", "reading":"ryo, tabi"},
  {"kanji":"族", "meaning":"Family, tribe", "reading":"zoku"},
  {"kanji":"昔", "meaning":"Long ago", "reading":"seki, shaku, mukashi"},
  {"kanji":"昭", "meaning":"Bright, clear", "reading":"shō"},
  {"kanji":"暑", "meaning":"Hot", "reading":"sho, atsui"},
  {"kanji":"暗", "meaning":"Dark", "reading":"an, kura-i"},
  {"kanji":"曲", "meaning":"Song, bend", "reading":"kyoku, ma-garu"},
  {"kanji":"有", "meaning":"Exist, to have", "reading":"yū, a-ru"},
  {"kanji":"服", "meaning":"Clothing, to serve", "reading":"fuku"},
  {"kanji":"期", "meaning":"Period, term", "reading":"ki"},
  {"kanji":"板", "meaning":"Board", "reading":"han, ban, ita"},
  {"kanji":"柱", "meaning":"Pillar", "reading":"chū, hashira"},
  {"kanji":"根", "meaning":"Root", "reading":"kon, ne"},
  {"kanji":"薬", "meaning":"Medicine", "reading":"yaku, kusuri"},

  {"kanji":"業", "meaning":"Work, business", "reading":"gyō"},
  {"kanji":"様", "meaning":"State, appearance", "reading":"yō, sama"},
  {"kanji":"横", "meaning":"Horizontal", "reading":"ō, yoko"},
  {"kanji":"橋", "meaning":"Bridge", "reading":"kyō, hashi"},
  {"kanji":"次", "meaning":"Next", "reading":"ji, tsugi, tsu-gu"},
  {"kanji":"歯", "meaning":"Tooth", "reading":"shi, ha"},
  {"kanji":"死", "meaning":"Death", "reading":"shi, shi-nu"},
  {"kanji":"氷", "meaning":"Ice", "reading":"hyō, kōri"},
  {"kanji":"決", "meaning":"To decide", "reading":"ketsu, ki-meru"},
  {"kanji":"油", "meaning":"Oil", "reading":"yu, abura"},
  {"kanji":"波", "meaning":"Wave", "reading":"ha, nami"},
  {"kanji":"注", "meaning":"To pour", "reading":"chū, soso-gu"},
  {"kanji":"泳", "meaning":"To swim", "reading":"ei, oyo-gu"},
  {"kanji":"洋", "meaning":"Ocean, western", "reading":"yō"},
  {"kanji":"流", "meaning":"Flow, to flow", "reading":"ryū, naga-reru"},
  {"kanji":"消", "meaning":"To extinguish, to erase", "reading":"shō, ki-eru, ke-su"},
  {"kanji":"深", "meaning":"Deep", "reading":"shin, fuka-i"},
  {"kanji":"温", "meaning":"Warm", "reading":"on, atata-kai"},
  {"kanji":"港", "meaning":"Port, harbor", "reading":"kō, minato"},
  {"kanji":"湖", "meaning":"Lake", "reading":"ko, mizūmi"},
  {"kanji":"湯", "meaning":"Hot water", "reading":"tō, yu"},
  {"kanji":"漢", "meaning":"China", "reading":"kan"},
  {"kanji":"炭", "meaning":"Charcoal", "reading":"tan, sumi"},
  {"kanji":"物", "meaning":"Thing, object", "reading":"butsu, motsu, mono"},
  {"kanji":"球", "meaning":"Ball, sphere", "reading":"kyū, tama"},
  {"kanji":"由", "meaning":"Cause, reason", "reading":"yū, yu, yoshi"},
  {"kanji":"申", "meaning":"To say", "reading":"shin, mō-su"},
  {"kanji":"界", "meaning":"World, boundary", "reading":"kai"},
  {"kanji":"畑", "meaning":"Field, farm", "reading":"hata, hatake"},
  {"kanji":"病", "meaning":"Illness", "reading":"byō, yamai"},
  {"kanji":"発", "meaning":"Departure, to emit", "reading":"hatsu"},
  {"kanji":"登", "meaning":"To climb", "reading":"tō, to, nobor-u"},
  {"kanji":"皮", "meaning":"Skin", "reading":"hi, kawa"},
  {"kanji":"皿", "meaning":"Plate", "reading":"bei, sara"},
  {"kanji":"相", "meaning":"Mutual, appearance", "reading":"sō, ai"},
  {"kanji":"県", "meaning":"Prefecture", "reading":"ken, ka-keru"},
  {"kanji":"真", "meaning":"True, real", "reading":"shin, ma"},
  {"kanji":"着", "meaning":"To wear, to arrive", "reading":"chaku, ki-ru, tsu-ku"},
  {"kanji":"短", "meaning":"Short", "reading":"tan, mijika-i"},
  {"kanji":"研", "meaning":"To polish, to sharpen", "reading":"ken, to-gu"},
  {"kanji":"礼", "meaning":"Courtesy, gratitude", "reading":"rei"},
  {"kanji":"神", "meaning":"God", "reading":"shin, jin, kami"},
  {"kanji":"祭", "meaning":"Festival, to celebrate", "reading":"sai, matsuri"},
  {"kanji":"福", "meaning":"Happiness, welfare", "reading":"fuku"},
  {"kanji":"秒", "meaning":"Second (unit of time)", "reading":"byō"},
  {"kanji":"究", "meaning":"To research, to investigate", "reading":"kyū, kiwa-meru"},
  {"kanji":"章", "meaning":"Chapter, badge", "reading":"shō"},
  {"kanji":"童", "meaning":"Child", "reading":"dō, warabe"},
  {"kanji":"笛", "meaning":"Flute, whistle", "reading":"teki, fue"},
  {"kanji":"第", "meaning":"(Prefix for ordinals)", "reading":"dai"},
  {"kanji":"筆", "meaning":"Brush, writing brush", "reading":"hitsu, fude"},
  {"kanji":"等", "meaning":"Class, rank", "reading":"tō, hito-shii"},
  {"kanji":"箱", "meaning":"Box", "reading":"sō, hako"},
  {"kanji":"級", "meaning":"Class, rank", "reading":"kyū"},
  {"kanji":"終", "meaning":"End, to finish", "reading":"shū, o-waru"},
  {"kanji":"緑", "meaning":"Green", "reading":"ryoku, midori"},
  {"kanji":"練", "meaning":"To train, to practice", "reading":"ren, ne-ru"},
  {"kanji":"羊", "meaning":"Sheep", "reading":"yō, hitsuji"},
  {"kanji":"美", "meaning":"Beauty", "reading":"bi, utsuku-shii"},
  {"kanji":"習", "meaning":"To learn", "reading":"shū, nara-u"},
  {"kanji":"者", "meaning":"Person, someone", "reading":"sha, mono"},
  {"kanji":"育", "meaning":"To raise, to bring up", "reading":"iku, soda-tsu"},
  {"kanji":"苦", "meaning":"Suffering, bitter", "reading":"ku, kuru-shii, niga-i"},
  {"kanji":"荷", "meaning":"Luggage, burden", "reading":"ka, ni"},
  {"kanji":"落", "meaning":"To fall", "reading":"raku, o-chiru"},
  {"kanji":"葉", "meaning":"Leaf", "reading":"yō, ha"},
  {"kanji":"薬", "meaning":"Medicine", "reading":"yaku, kusuri"},
  {"kanji":"血", "meaning":"Blood", "reading":"ketsu, chi"},
  {"kanji":"表", "meaning":"Surface, to express", "reading":"hyō, omote, arawa-su"},
  {"kanji":"詩", "meaning":"Poetry, poem", "reading":"shi, uta"},
  {"kanji":"調", "meaning":"Tone, melody", "reading":"chō, shira-beru"},
  {"kanji":"談", "meaning":"To talk, to discuss", "reading":"dan"},
  {"kanji":"豆", "meaning":"Bean", "reading":"tō, zu, mame"},
  {"kanji":"負", "meaning":"To lose, to be defeated", "reading":"fu, ma-keru, o-u"},
  {"kanji":"起", "meaning":"To rise, to wake", "reading":"ki, o-kiru"},
  {"kanji":"路", "meaning":"Road, path", "reading":"ro, ji"},
  {"kanji":"身", "meaning":"Body", "reading":"shin, mi"},
  {"kanji":"転", "meaning":"To turn, to roll", "reading":"ten, koro-bu"},
  {"kanji":"軽", "meaning":"Light, lightweight", "reading":"kei, karu-i"},
  {"kanji":"農", "meaning":"Agriculture", "reading":"nō"},
  {"kanji":"返", "meaning":"To return, to repay", "reading":"hen, kae-su"},
  {"kanji":"追", "meaning":"To chase, to follow", "reading":"tsui, o-u"},
  {"kanji":"送", "meaning":"To send", "reading":"sō, oku-ru"},
  {"kanji":"速", "meaning":"Fast, quick", "reading":"soku, haya-i"},
  {"kanji":"進", "meaning":"To advance, to progress", "reading":"shin, susu-mu"},
  {"kanji":"遊", "meaning":"To play", "reading":"yū, aso-bu"},
  {"kanji":"運", "meaning":"Luck, to carry", "reading":"un, hako-bu"},
  {"kanji":"部", "meaning":"Part, department", "reading":"bu"},
  {"kanji":"都", "meaning":"Capital, metropolis", "reading":"to, tsu, miyako"},
  {"kanji":"配", "meaning":"To distribute, to deliver", "reading":"hai, kuba-ru"},
  {"kanji":"酒", "meaning":"Alcohol, sake", "reading":"shu, sake, saka"},
  {"kanji":"重", "meaning":"Heavy, important", "reading":"jū, chō, omo-i, kasa-neru"},
  {"kanji":"鉄", "meaning":"Iron", "reading":"tetsu"},
  {"kanji":"銀", "meaning":"Silver", "reading":"gin, shirogane"},
  {"kanji":"開", "meaning":"To open", "reading":"kai, hira-ku, a-ku"},
  {"kanji":"院", "meaning":"Institution", "reading":"in"},
  {"kanji":"陽", "meaning":"Sun, positive", "reading":"yō, hi"},
  {"kanji":"階", "meaning":"Floor, stairs", "reading":"kai, kizahashi"},
  {"kanji":"集", "meaning":"To gather", "reading":"shū, atsumaru"},
  {"kanji":"面", "meaning":"Face, surface", "reading":"men, omote, tsura"},
  {"kanji":"題", "meaning":"Topic, subject", "reading":"dai"},
  {"kanji":"飲", "meaning":"To drink", "reading":"in, no-mu"},
  {"kanji":"館", "meaning":"Building", "reading":"kan, tate"},
  {"kanji":"駅", "meaning":"Station", "reading":"eki"},
  {"kanji":"鼻", "meaning":"Nose", "reading":"bi, hana"},
{"kanji":"茨", "meaning": "Dorn, Stachel, Dornbusch", "reading": "shi, ibara"},
{"kanji":"媛", "meaning": "Prinzessin", "reading": "en, on, hime"},
{"kanji":"岡", "meaning": "Hügel, Anhöhe", "reading": "kō, oka"},
{"kanji":"潟", "meaning": "Lagune", "reading": "seki, kata"},
{"kanji":"岐", "meaning": "Gabelung, Abzweigung", "reading": "ki, mata, takashi"},
{"kanji":"熊", "meaning": "Bär", "reading": "yū, u, kuma"},
{"kanji":"香", "meaning": "Duft, Geruch [Weihrauch]", "reading": "ka [kō], kaori"},
{"kanji":"佐", "meaning": "Hilfe, Beistand", "reading": "sa, tasuke"},
{"kanji":"埼", "meaning": "Spitze, Landzunge", "reading": "sai, saki"},
{"kanji":"崎", "meaning": "Spitze, Landzunge", "reading": "saki"},
{"kanji":"滋", "meaning": "verleihen, gedeihen", "reading": "shige-ru"},
{"kanji":"鹿", "meaning": "Hirsch", "reading": "shika, ka"},
{"kanji":"縄", "meaning": "Seil", "reading": "nawa"},
{"kanji":"井", "meaning": "Brunnen", "reading": "sei, shō, i"},
{"kanji":"沖", "meaning": "offenes Meer", "reading": "chū, oki"},
{"kanji":"栃", "meaning": "Baum (die Kastanie)", "reading": "tochi"},
{"kanji":"奈", "meaning": "Nara (Stadt)", "reading": "na"},
{"kanji":"梨", "meaning": "Birne, Birnbaum", "reading": "ri, nashi"},
{"kanji":"阪", "meaning": "Hang, Steigung, Hügel", "reading": "han, saka"},
{"kanji":"阜", "meaning": "Hügel, Anhöhe", "reading": "fū, tsukasa"},
{"kanji":"不", "meaning": "nicht", "reading": "fu, bu"},
{"kanji":"争", "meaning": "kämpfen", "reading": "sō, araso-u"},
{"kanji":"付", "meaning": "anbringen", "reading": "fu, tsu-ku"},
{"kanji":"令", "meaning": "Befehl, Gebot", "reading": "rei"},
{"kanji":"以", "meaning": "durch, mittels", "reading": "i"},
{"kanji":"仲", "meaning": "Beziehung", "reading": "chū, naka"},
{"kanji":"伝", "meaning": "übermitteln, überliefern", "reading": "den, tsuta-eru"},
{"kanji":"位", "meaning": "Rang", "reading": "i, kurai"},
{"kanji":"低", "meaning": "niedrig", "reading": "tei, hiku-i"},
{"kanji":"例", "meaning": "Beispiel", "reading": "rei, tato-eru"},
{"kanji":"便", "meaning": "Bequemlichkeit, Brief", "reading": "ben, bin, tayo-ri"},
{"kanji":"信", "meaning": "Vertrauen", "reading": "shin"},
{"kanji":"倉", "meaning": "Lagerhaus", "reading": "sō, kura"},
{"kanji":"候", "meaning": "Wetter, warten auf", "reading": "kō"},
{"kanji":"借", "meaning": "sich ausleihen", "reading": "shaku, ka-riru"},
{"kanji":"健", "meaning": "gesund", "reading": "ken"},
{"kanji":"側", "meaning": "Seite", "reading": "soku, kawa"},
{"kanji":"働", "meaning": "arbeiten", "reading": "dō, hatara-ku"},
{"kanji":"億", "meaning": "hundert Millionen", "reading": "oku"},
{"kanji":"兆", "meaning": "Omen, Billion", "reading": "chō, kiza-shi"},
{"kanji":"児", "meaning": "Säugling", "reading": "ji, ni"},
{"kanji":"共", "meaning": "gemeinsam", "reading": "kyō, tomo"},
{"kanji":"兵", "meaning": "Soldat", "reading": "hei, hyō, tsuwamono"},
{"kanji":"典", "meaning": "Zeremonie, Regel", "reading": "ten"},
{"kanji":"冷", "meaning": "kühl", "reading": "rei, tsume-tai, hi-eru, sa-meru"},
{"kanji":"城", "meaning": "Burg, Schloss", "reading": "jō, shiro"},
{"kanji":"初", "meaning": "Anfang", "reading": "sho, hatsu, haji-me"},
{"kanji":"別", "meaning": "trennen", "reading": "betsu, waka-reru"},
{"kanji":"利", "meaning": "Profit", "reading": "ri"},
{"kanji":"刷", "meaning": "drucken", "reading": "satsu, su-ru"},
{"kanji":"副", "meaning": "Vize-", "reading": "fuku"},
{"kanji":"功", "meaning": "Verdienst", "reading": "kō"},
{"kanji":"加", "meaning": "addieren", "reading": "ka, kuwa-eru"},
{"kanji":"努", "meaning": "sich anstrengen", "reading": "dō, tsuto-meru"},
{"kanji":"労", "meaning": "Arbeit, Mühe", "reading": "rō, negira-u"},
{"kanji":"勇", "meaning": "mutig", "reading": "yū, isa-mu"},
{"kanji":"包", "meaning": "einwickeln", "reading": "hō, tsutsu-mu"},
{"kanji":"卒", "meaning": "(Schul-)Abschluss", "reading": "sotsu"},
{"kanji":"協", "meaning": "Zusammenarbeit", "reading": "kyō"},
{"kanji":"単", "meaning": "einfach", "reading": "tan"},
{"kanji":"博", "meaning": "Ausstellung, Dr. (Titel)", "reading": "haku"},
{"kanji":"印", "meaning": "Stempel, Indien", "reading": "in, shirushi"},
{"kanji":"参", "meaning": "teilnehmen", "reading": "san, mai-ru"},
{"kanji":"司", "meaning": "Direktor, Staatsdiener", "reading": "shi"},
{"kanji":"各", "meaning": "jeder, jeweils", "reading": "kaku, ono-ono"},
{"kanji":"周", "meaning": "Umfang, herumgehen um", "reading": "shū, mawa-ri"},
{"kanji":"唱", "meaning": "anrufen", "reading": "shō, tona-eru"},
{"kanji":"器", "meaning": "Behälter", "reading": "ki, utsuwa"},
{"kanji":"固", "meaning": "hart", "reading": "ko, kata-maru"},
{"kanji":"塩", "meaning": "Salz", "reading": "en, shio"},
{"kanji":"変", "meaning": "ändern, seltsam", "reading": "hen, ka-waru"},
{"kanji":"夫", "meaning": "Ehemann", "reading": "fu, fū, bu, otto"},
{"kanji":"失", "meaning": "verlieren", "reading": "shitsu, ushina-u"},
{"kanji":"好", "meaning": "mögen", "reading": "kō, su-ku, kono-mu"},
{"kanji":"季", "meaning": "Jahreszeit", "reading": "ki"},
{"kanji":"孫", "meaning": "Enkel", "reading": "son, mago"},
{"kanji":"完", "meaning": "perfekt", "reading": "kan"},
{"kanji":"官", "meaning": "Beamter, Bürokrat", "reading": "kan"},
{"kanji":"害", "meaning": "Schaden", "reading": "gai"},
{"kanji":"察", "meaning": "raten, annehmen", "reading": "satsu"},
{"kanji":"巣", "meaning": "Nest", "reading": "sō, su"},
{"kanji":"差", "meaning": "Unterschied", "reading": "sa"},
{"kanji":"希", "meaning": "Hoffnung, selten", "reading": "ki, mare"},
{"kanji":"席", "meaning": "Sitz", "reading": "seki"},
{"kanji":"帯", "meaning": "Gürtel", "reading": "tai, obi"},
{"kanji":"底", "meaning": "Boden", "reading": "tei, soko"},
{"kanji":"府", "meaning": "Stadtpräfektur", "reading": "fu"},
{"kanji":"康", "meaning": "friedlich", "reading": "kō"},
{"kanji":"建", "meaning": "erbauen", "reading": "ken, ta-teru"},
{"kanji":"径", "meaning": "Durchmesser", "reading": "kei"},
{"kanji":"徒", "meaning": "zu Fuß, sinnlos", "reading": "to"},
{"kanji":"必", "meaning": "gewiss", "reading": "hitsu, kanara-zu"},
{"kanji":"念", "meaning": "Gedanke", "reading": "nen"},
{"kanji":"愛", "meaning": "Liebe", "reading": "ai"},
{"kanji":"成", "meaning": "werden", "reading": "sei, na-ru"},
{"kanji":"戦", "meaning": "Krieg", "reading": "sen, ikusa, tataka-u"},
{"kanji":"折", "meaning": "falten", "reading": "setsu, o-ru"},
{"kanji":"挙", "meaning": "aufsteigen, erheben", "reading": "kyo, a-geru"},
{"kanji":"改", "meaning": "reformieren", "reading": "kai, arata-meru"},
{"kanji":"敗", "meaning": "Niederlage", "reading": "hai, yabu-reru"},
{"kanji":"散", "meaning": "zerstreuen", "reading": "san, chi-ru"},
{"kanji":"料", "meaning": "Gebühr", "reading": "ryō"},
{"kanji":"旗", "meaning": "Flagge", "reading": "ki, hata"},
{"kanji":"昨", "meaning": "gestern", "reading": "saku"},
{"kanji":"景", "meaning": "Szene, Landschaft", "reading": "kei"},
{"kanji":"最", "meaning": "am meisten (Superlativ)", "reading": "sai, mo, motto-mo"},
{"kanji":"望", "meaning": "Hoffnung, in die Ferne schauen", "reading": "bō, nozo-mu"},
{"kanji":"束", "meaning": "Bündel", "reading": "soku, taku"},
{"kanji":"散", "meaning": "zerstreuen", "reading": "san, chi-ru"},

{"kanji":"未", "meaning": "noch", "reading": "mi, ima-da"},
  {"kanji":"末", "meaning": "Ende", "reading": "matsu, sue"},
  {"kanji":"札", "meaning": "Zettel, Geldschein, Etikett", "reading": "satsu, fuda"},
  {"kanji":"材", "meaning": "Holz, Material", "reading": "zai"},
  {"kanji":"束", "meaning": "Bündel", "reading": "soku, taba, tsuka"},
  {"kanji":"松", "meaning": "Kiefer (Baum)", "reading": "shō, matsu"},
  {"kanji":"果", "meaning": "Ergebnis, Frucht", "reading": "ka, ha-tasu"},
  {"kanji":"栄", "meaning": "Ruhm, gedeihen", "reading": "ei, saka-eru"},
  {"kanji":"案", "meaning": "Vorschlag, Plan", "reading": "an"},
  {"kanji":"梅", "meaning": "Pflaume", "reading": "bai, ume"},
  {"kanji":"械", "meaning": "Mechanismus", "reading": "kai"},
  {"kanji":"極", "meaning": "Pol, extrem", "reading": "kyoku, kiwa-meru"},
  {"kanji":"標", "meaning": "Markierungspfosten", "reading": "hyō"},
  {"kanji":"機", "meaning": "Maschine", "reading": "ki, hata"},
  {"kanji":"欠", "meaning": "fehlen", "reading": "ketsu, ka-keru"},
  {"kanji":"残", "meaning": "Rest", "reading": "zan, noko-ru"},
  {"kanji":"氏", "meaning": "Familienname", "reading": "shi, uji"},
  {"kanji":"民", "meaning": "Volk", "reading": "min, tami"},
  {"kanji":"求", "meaning": "fordern", "reading": "kyū, moto-mu"},
  {"kanji":"治", "meaning": "regieren", "reading": "chi, ji, osa-meru, nao-ru"},
  {"kanji":"法", "meaning": "Gesetz, Methode", "reading": "hō"},
  {"kanji":"泣", "meaning": "weinen", "reading": "kyū, na-ku"},
  {"kanji":"浅", "meaning": "seicht, oberflächlich", "reading": "sen, asa-i"},
  {"kanji":"浴", "meaning": "baden", "reading": "yoku, a-biru"},
  {"kanji":"清", "meaning": "rein, sauber", "reading": "sei, shō, kiyo-raka"},
  {"kanji":"満", "meaning": "voll", "reading": "man, mi-chiru"},
  {"kanji":"漁", "meaning": "fischen, Fischfang", "reading": "ryō, gyo, asa-ru"},
  {"kanji":"灯", "meaning": "Lampe", "reading": "tō, hi"},
  {"kanji":"無", "meaning": "nichts", "reading": "mu, bu, na-i"},
  {"kanji":"然", "meaning": "so", "reading": "zen, nen, shika-shi"},
  {"kanji":"焼", "meaning": "backen", "reading": "shō, ya-ku"},
  {"kanji":"照", "meaning": "leuchten, scheinen", "reading": "shō, te-rasu"},
  {"kanji":"熱", "meaning": "Hitze", "reading": "netsu, atsui"},
  {"kanji":"牧", "meaning": "Weide, züchten", "reading": "boku, maki"},
  {"kanji":"特", "meaning": "speziell", "reading": "toku"},
  {"kanji":"産", "meaning": "gebären", "reading": "san, u-mu"},
  {"kanji":"的", "meaning": "Ziel, Zeilscheibe", "reading": "teki, mato"},
  {"kanji":"省", "meaning": "Ministerium, weglassen, sparen", "reading": "shō, sei, habu-ku"},
  {"kanji":"祝", "meaning": "feiern", "reading": "shuku, iwa-u"},
  {"kanji":"票", "meaning": "Votum", "reading": "hyō"},
  {"kanji":"種", "meaning": "Sorte, Saat", "reading": "shu, tane"},
  {"kanji":"積", "meaning": "ansammeln, anhäufen", "reading": "seki, tsu-mu"},
  {"kanji":"競", "meaning": "wetteifern", "reading": "kyō, kiso-u"},
  {"kanji":"笑", "meaning": "lachen", "reading": "shō, wara-u"},
  {"kanji":"管", "meaning": "Rohr", "reading": "kan, kuda"},
  {"kanji":"節", "meaning": "Abschnitt, Gelenk", "reading": "setsu, fushi"},
  {"kanji":"約", "meaning": "Versprechen, kürzen", "reading": "yaku"},
  {"kanji":"結", "meaning": "binden", "reading": "ketsu, musu-bu, yu-u"},
  {"kanji":"給", "meaning": "Gehalt", "reading": "kyū, tama-u"},
  {"kanji":"続", "meaning": "fortsetzen", "reading": "zoku, tsuzu-ku"},
  {"kanji":"置", "meaning": "stellen, legen", "reading": "chi, o-ku"},
  {"kanji":"老", "meaning": "alter Mensch", "reading": "rō, o-iru"},
  {"kanji":"臣", "meaning": "Untertan, Gefolgsmann", "reading": "shin"},
  {"kanji":"良", "meaning": "gut", "reading": "ryō, yo-i"},
  {"kanji":"芸", "meaning": "Kunst", "reading": "gei"},
  {"kanji":"芽", "meaning": "Knospe", "reading": "ga, me"},
  {"kanji":"英", "meaning": "England", "reading": "ei"},
  {"kanji":"菜", "meaning": "Gemüse", "reading": "sai, na"},
  {"kanji":"街", "meaning": "Stadt, Straße", "reading": "gai, machi"},
  {"kanji":"衣", "meaning": "Kleid", "reading": "i, koromo"},
  {"kanji":"要", "meaning": "brauchen", "reading": "yō, i-ru"},
  {"kanji":"覚", "meaning": "merken, erinnern", "reading": "kaku, obo-eru, sa-meru"},
  {"kanji":"観", "meaning": "beobachten", "reading": "kan, mi-ru"},
  {"kanji":"訓", "meaning": "Belehrung, Anweisung", "reading": "kun"},
  {"kanji":"試", "meaning": "versuchen, probieren", "reading": "shi, kokoro-miru, tame-su"},
  {"kanji":"説", "meaning": "Erklärung, Theorie", "reading": "setsu, to-ku"},
  {"kanji":"課", "meaning": "Abteilung, Lektion", "reading": "ka"},
  {"kanji":"議", "meaning": "Beratung, Vorschlag", "reading": "gi"},
  {"kanji":"貨", "meaning": "Fracht", "reading": "ka"},
  {"kanji":"軍", "meaning": "Armee", "reading": "gun"},
  {"kanji":"静", "meaning": "ruhig", "reading": "sei, shizu-ka"},
  {"kanji":"順", "meaning": "gehorchen", "reading": "jun"},
  {"kanji":"願", "meaning": "bitten, wünschen, Gesuch", "reading": "gan, nega-u"},
  {"kanji":"類", "meaning": "Sorte", "reading": "rui"},
  {"kanji":"飛", "meaning": "fliegen", "reading": "hi, to-bu"},
  {"kanji":"飯", "meaning": "Nahrung, gekochter Reis", "reading": "han, meshi"},
  {"kanji":"養", "meaning": "aufziehen (Kinder)", "reading": "yō, yashina-u"},
  {"kanji":"験", "meaning": "testen, Effekt", "reading": "ken"},
  {"kanji":"賀", "meaning": "Gratulation", "reading": "ga"},
  {"kanji":"群", "meaning": "Herde, Gruppe", "reading": "gun, mu-reru"},
  {"kanji":"輪", "meaning": "Rad", "reading": "rin, wa"},
  {"kanji":"辞", "meaning": "Wort, absagen", "reading": "ji, ya-meru"},
  {"kanji":"辺", "meaning": "Gegend, Umgebung", "reading": "hen, ata-ri"},
  {"kanji":"連", "meaning": "mitnehmen", "reading": "ren, tsu-reru, tsura-neru"},
  {"kanji":"達", "meaning": "erreichen, Plural", "reading": "tachi"},
  {"kanji":"選", "meaning": "auswählen", "reading": "sen, era-bu"},
  {"kanji":"郡", "meaning": "Landkreis", "reading": "gun"},
  {"kanji":"量", "meaning": "Quantität", "reading": "ryō"},
  {"kanji":"録", "meaning": "aufzeichnen", "reading": "roku"},
  {"kanji":"鏡", "meaning": "Spiegel", "reading": "kyō, kagami"},
  {"kanji":"関", "meaning": "Zusammenhang", "reading": "kan, seki"},
  {"kanji":"陸", "meaning": "Festland", "reading": "riku"},
  {"kanji":"隊", "meaning": "Gruppe, Truppe", "reading": "tai"},
  {"kanji":"徳", "meaning": "Tugend", "reading": "toku"},
  {"kanji":"富", "meaning": "Reichtum", "reading": "fu, tomi"},
# Fünftes Schuljahr (193 kanji)
{"kanji":"毒", "meaning": "Gift", "reading": "	doku	"},
{"kanji":"歴", "meaning": "Lehrplan; zeitlicher Ablauf", "reading": "	reki	"},
{"kanji":"脈", "meaning": "Puls; Vene", "reading": "	myaku	"},
{"kanji":"粉", "meaning": "Mehl", "reading": "	fun	ko, kona"},
{"kanji":"喜", "meaning": "sich freuen", "reading": "	ki	yoroko-bu"},
{"kanji":"得", "meaning": "erhalten", "reading": "	toku	e-ru"},
{"kanji":"貯", "meaning": "sparen, aufbewahren", "reading": "	cho	ta-meru"},
{"kanji":"費", "meaning": "Ausgaben", "reading": "	hi	tsui-yasu"},
{"kanji":"象", "meaning": "Elefant; Gestalt", "reading": "	zō, shō	"},
{"kanji":"殺", "meaning": "töten", "reading": "	satsu	koro-su"},
{"kanji":"停", "meaning": "anhalten", "reading": "	tei	"},
{"kanji":"告", "meaning": "bekannt machen, melden", "reading": "	koku	tsu-geru"},
{"kanji":"堂", "meaning": "öffentliche", "reading": " Halle	dō	"},
{"kanji":"航", "meaning": "Navigation", "reading": "	kō	"},
{"kanji":"賞", "meaning": "Preis", "reading": "	shō	"},
{"kanji":"型", "meaning": "Modell, Typ", "reading": "	kei	kata"},
{"kanji":"救", "meaning": "retten", "reading": "	kyū	suku-u"},
{"kanji":"囲", "meaning": "einschließen", "reading": "	i	kako-u"},
{"kanji":"紀", "meaning": "Chronik", "reading": "	ki	"},
{"kanji":"史", "meaning": "Geschichte, Chronik", "reading": "	shi	"},
{"kanji":"勢", "meaning": "Energie", "reading": "	sei	ikio-i"},
{"kanji":"厚", "meaning": "dick; herzlich", "reading": "	kō	atsu-i"},
{"kanji":"句", "meaning": "Redensart", "reading": "	ku	"},
{"kanji":"可", "meaning": "möglich sein, -bar", "reading": "	ka	"},
{"kanji":"営", "meaning": "durchführen", "reading": "	ei	itona-mu"},
{"kanji":"因", "meaning": "Ursache", "reading": "	in	yo-ru"},
{"kanji":"団", "meaning": "Gruppierung", "reading": "	dan, ton	"},
{"kanji":"圧", "meaning": "Druck", "reading": "	atsu	"},
{"kanji":"在", "meaning": "existieren", "reading": "	zai	a-ru"},
{"kanji":"均", "meaning": "ausbalanciert, gleich", "reading": "	kin	"},
{"kanji":"基", "meaning": "Fundament", "reading": "	ki	moto-zuku"},
{"kanji":"報", "meaning": "Benachrichtigung; sich rächen", "reading": "	hō	muku-iru"},
{"kanji":"境", "meaning": "Grenze", "reading": "	kyō	sakai"},
{"kanji":"墓", "meaning": "Grab", "reading": "	bo	haka"},
{"kanji":"増", "meaning": "zunehmen", "reading": "	zō	ma-su, fu-eru"},
{"kanji":"夢", "meaning": "Traum", "reading": "	mu	yume"},
{"kanji":"妻", "meaning": "(eigene) Ehefrau", "reading": "	sai	tsuma"},
{"kanji":"婦", "meaning": "Ehefrau", "reading": "; Dame	fu	"},
{"kanji":"容", "meaning": "Inhalt", "reading": "	yō	"},
{"kanji":"寄", "meaning": "sich nähern", "reading": "	ki	yo-ru"},
{"kanji":"備", "meaning": "ausrüsten", "reading": "	bi	sona-eru"},
{"kanji":"導", "meaning": "führen, leiten", "reading": "	dō	michibi-ku"},
{"kanji":"居", "meaning": "sich befinden, existieren", "reading": "	kyo	i-ru"},
{"kanji":"属", "meaning": "angehören", "reading": "	zoku	"},
{"kanji":"布", "meaning": "Stoff, Tuch", "reading": "	fu	nuno"},
{"kanji":"師", "meaning": "Fachmann, Lehrer", "reading": "	shi	"},
{"kanji":"常", "meaning": "normal", "reading": "	jō	tsune"},
{"kanji":"幹", "meaning": "(Baum)stamm; Hauptteil", "reading": "	kan	miki"},
{"kanji":"序", "meaning": "Reihenfolge; Vorrede", "reading": "	jo	"},
{"kanji":"弁", "meaning": "Klappe; Sprechen", "reading": "	ben	"},
{"kanji":"張", "meaning": "(auf)spannen", "reading": "	chō	ha-ru"},
{"kanji":"往", "meaning": "reisen, fortgehen", "reading": "	ō	"},
{"kanji":"復", "meaning": "wiederaufnehmen, zurückkehren", "reading": "	fuku	"},
{"kanji":"個", "meaning": "Individuum", "reading": "	ko	"},
{"kanji":"志", "meaning": "Wille, Absicht", "reading": "	shi	kokorozashi"},
{"kanji":"応", "meaning": "Antwort", "reading": "	ō	"},
{"kanji":"快", "meaning": "freudig", "reading": "	kai	kokoroyo-i"},
{"kanji":"性", "meaning": "Geschlecht", "reading": "	sei, shō	saga"},
{"kanji":"務", "meaning": "dienen; Pflicht", "reading": "	mu	tsuto-meru"},
{"kanji":"情", "meaning": "Gefühl", "reading": "	jō	nasa-ke"},
{"kanji":"態", "meaning": "Zustand, Lage", "reading": "	tai	"},
{"kanji":"慣", "meaning": "sich gewöhnen", "reading": "	kan	na-reru"},
{"kanji":"効", "meaning": "Wirkung", "reading": "	kō	ki-ku"},
{"kanji":"技", "meaning": "Fähigkeit", "reading": "	gi	waza"},
{"kanji":"招", "meaning": "herbeiwinken", "reading": "	shō	mane-ku"},
{"kanji":"授", "meaning": "unterrichten", "reading": "	ju	sazu-keru"},
{"kanji":"採", "meaning": "aufnehmen, pflücken", "reading": "	sai	to-ru"},
{"kanji":"接", "meaning": "zusammenfügen", "reading": "	setsu	tsu-gu"},
{"kanji":"提", "meaning": "vorlegen", "reading": "	tei	sa-geru"},
{"kanji":"損", "meaning": "Verlust", "reading": "	son	soko-neru"},
{"kanji":"支", "meaning": "stützen", "reading": "	shi	sasa-eru"},
{"kanji":"政", "meaning": "Politik", "reading": "	sei	matsurigoto"},
{"kanji":"故", "meaning": "Ursache, Umstände", "reading": "	ko	yue"},
{"kanji":"則", "meaning": "Regel", "reading": "	soku	notto-ru"},
{"kanji":"断", "meaning": "abschneiden", "reading": "	dan	ta-tsu, kotowa-ru"},
{"kanji":"旧", "meaning": "alte Zeiten", "reading": "	kyū	"},
{"kanji":"易", "meaning": "einfach, leicht", "reading": "	eki	yasa-shii"},
{"kanji":"暴", "meaning": "Ausbruch; Gewalt", "reading": "	bō	aba-ku"},
{"kanji":"条", "meaning": "Klausel", "reading": "	jō	"},
{"kanji":"枝", "meaning": "Ast, Zweig", "reading": "	shi	eda"},
{"kanji":"査", "meaning": "untersuchen", "reading": "	sa	"},
{"kanji":"格", "meaning": "Regel; Status", "reading": "	kaku	"},
{"kanji":"桜", "meaning": "Kirsche", "reading": "	ō	sakura"},
{"kanji":"検", "meaning": "inspizieren", "reading": "	ken	"},
{"kanji":"構", "meaning": "bauen, konstruieren", "reading": "	kō	kama-eru"},
{"kanji":"武", "meaning": "Militär", "reading": "	bu, mu	"},
{"kanji":"比", "meaning": "vergleichen", "reading": "	hi	kura-beru"},
{"kanji":"永", "meaning": "lange Zeit, Ewigkeit", "reading": "	ei	naga-i"},
{"kanji":"河", "meaning": "Fluss, Strom", "reading": "	ka	kawa"},
{"kanji":"液", "meaning": "Flüssigkeit, Saft", "reading": "	eki	"},
{"kanji":"混", "meaning": "vermischen", "reading": "	kon	ma-zaru"},
{"kanji":"減", "meaning": "verringern", "reading": "	gen	he-ru"},
{"kanji":"測", "meaning": "messen", "reading": "	soku	haka-ru"},
{"kanji":"準", "meaning": "gleichwertig; Semi(finale)", "reading": "	jun	"},
{"kanji":"演", "meaning": "aufführen", "reading": "	en	"},
{"kanji":"潔", "meaning": "unbefleckt", "reading": "	ketsu	isagiyo-i"},
{"kanji":"災", "meaning": "Unheil, Katastrophe", "reading": "	sai	wazawa-i"},
{"kanji":"燃", "meaning": "brennen", "reading": "	nen	mo-eru"},
{"kanji":"版", "meaning": "Druckplatte", "reading": "	han	"},
{"kanji":"犯", "meaning": "Verbrechen", "reading": "	han	oka-su"},
{"kanji":"状", "meaning": "Form", "reading": "	jō	"},
{"kanji":"独", "meaning": "allein; Deutschland", "reading": "	doku	hito-ri"},
{"kanji":"率", "meaning": "Verhältnis, Rate", "reading": "	ritsu, sotsu	hiki-iru"},
{"kanji":"現", "meaning": "gegenwärtig; erscheinen", "reading": "	gen	arawa-reru"},
{"kanji":"留", "meaning": "aufhalten, anhalten", "reading": "	ryū, ru	todo-maru"},
{"kanji":"略", "meaning": "Abkürzung", "reading": "	ryaku	"},
{"kanji":"益", "meaning": "Gewinn, Nutzen", "reading": "	eki	"},
{"kanji":"眼", "meaning": "Augapfel", "reading": "	gan	me"},
{"kanji":"破", "meaning": "zerreißen, brechen", "reading": "	ha	yabu-ru"},
{"kanji":"確", "meaning": "sicher, gewiss", "reading": "	kaku	tashi-ka"},
{"kanji":"示", "meaning": "zeigen", "reading": "	shi	shime-su"},
{"kanji":"祖", "meaning": "Vorfahr", "reading": "	so	"},
{"kanji":"禁", "meaning": "Verbot", "reading": "	kin	"},
{"kanji":"移", "meaning": "ändern, wechseln", "reading": "	i	utsu-ru"},
{"kanji":"程", "meaning": "Ausmaß", "reading": "	tei	hodo"},
{"kanji":"税", "meaning": "Steuer", "reading": ", Zoll	zei	"},
{"kanji":"築", "meaning": "bauen", "reading": "	chiku	kizu-ku"},
{"kanji":"精", "meaning": "Energie; veredelt", "reading": "	sei	"},
{"kanji":"素", "meaning": "elementar, ursprünglich", "reading": "	su, so	moto"},
{"kanji":"経", "meaning": "hindurchgehen, vergehen", "reading": "	kei, kyō	he-ru"},
{"kanji":"統", "meaning": "Beziehung; herrschen", "reading": "	tō	su-beru"},
{"kanji":"絶", "meaning": "enden, aussterben", "reading": "	zetsu	ta-tsu"},
{"kanji":"綿", "meaning": "Baumwolle	men", "reading": "	wata"},
{"kanji":"総", "meaning": "allgemein, gesamt", "reading": "	sō	"},
{"kanji":"編", "meaning": "stricken; zusammenstellen", "reading": "	hen	a-mu"},
{"kanji":"績", "meaning": "Verdienste; (Seide) spinnen", "reading": "	seki	"},
{"kanji":"織", "meaning": "weben", "reading": "	shiki	o-ru"},
{"kanji":"罪", "meaning": "Verbrechen, Schuld", "reading": "	zai	tsumi"},
{"kanji":"制", "meaning": "Kontrolle", "reading": "	sei	"},
{"kanji":"義", "meaning": "Gerechtigkeit", "reading": "	gi	"},
{"kanji":"耕", "meaning": "(einen Acker) bestellen, pflügen", "reading": "	kō	tagaya-su"},
{"kanji":"職", "meaning": "Dienst, Anstellung", "reading": "	shoku	"},
{"kanji":"肥", "meaning": "Dünger", "reading": "	hi	ko-yasu"},
{"kanji":"能", "meaning": "Fähigkeit", "reading": "	nō	"},
{"kanji":"興", "meaning": "Amüsement, Unterhaltung", "reading": "	kyō	oko-su"},
{"kanji":"判", "meaning": "Gericht", "reading": "	han	waka-ru"},
{"kanji":"舎", "meaning": "Hütte, Herberge", "reading": "	sha	"},
{"kanji":"術", "meaning": "Kunst(fähigkeit)", "reading": "	jutsu	sube"},
{"kanji":"衛", "meaning": "verteidigen", "reading": "	ei	"},
{"kanji":"製", "meaning": "herstellen", "reading": "	sei	"},
{"kanji":"複", "meaning": "doppelt, mehrfach", "reading": "	fuku	"},
{"kanji":"規", "meaning": "Vorschrift", "reading": "	ki	"},
{"kanji":"解", "meaning": "aufknoten, lösen", "reading": "	ge, kai	to-ku"},
{"kanji":"設", "meaning": "gründen, einrichten", "reading": "	setsu	mou-keru"},
{"kanji":"許", "meaning": "erlauben", "reading": "	kyo	yuru-su"},
{"kanji":"証", "meaning": "Bestätigung, Beweis", "reading": "	shō	akashi"},
{"kanji":"評", "meaning": "Kritik, Beurteilung", "reading": "	hyō	"},
{"kanji":"講", "meaning": "Vorlesung", "reading": "	kō	"},
{"kanji":"謝", "meaning": "Dank; sich entschuldigen", "reading": "	sha	ayama-ru"},
{"kanji":"識", "meaning": "aufzeichnen; unterscheiden", "reading": "	shiki	"},
{"kanji":"護", "meaning": "verteidigen, schützen", "reading": "	go	mamo-ru"},
{"kanji":"豊", "meaning": "reichlich, üppig", "reading": "	hō	yuta-ka"},
{"kanji":"財", "meaning": "Geld, Besitz", "reading": "	zai	"},
{"kanji":"貧", "meaning": "arm; dürftig", "reading": "	hin	mazu-shii"},
{"kanji":"責", "meaning": "tadeln", "reading": "	seki	se-meru"},
{"kanji":"貸", "meaning": "verleihen", "reading": "	tai	ka-su"},
{"kanji":"貿", "meaning": "tauschen, handeln", "reading": "	bō	"},
{"kanji":"刊", "meaning": "veröffentlichen", "reading": "	kan	"},
{"kanji":"資", "meaning": "Mittel, Ressourcen", "reading": "	shi	"},
{"kanji":"賛", "meaning": "loben, zustimmen", "reading": "	san	"},
{"kanji":"質", "meaning": "Qualität; Pfand", "reading": "	shitsu	"},
{"kanji":"輸", "meaning": "transportieren", "reading": "	yu	"},
{"kanji":"述", "meaning": "äußern, erwähnen", "reading": "	jutsu	no-beru"},
{"kanji":"迷", "meaning": "Irrtum, sich verirren", "reading": "	mei	mayo-u"},
{"kanji":"再", "meaning": "wieder, Re-", "reading": "	sai, sa	futata-bi"},
{"kanji":"逆", "meaning": "umgekehrt, Gegenteil", "reading": "	gyaku	saka-rau"},
{"kanji":"造", "meaning": "bauen, herstellen", "reading": "	zō	tsuku-ru"},
{"kanji":"過", "meaning": "das Maß überschreiten", "reading": "	ka	su-giru, ayama-chi"},
{"kanji":"適", "meaning": "passend, entsprechend", "reading": "	teki	"},
{"kanji":"酸", "meaning": "Säure", "reading": "	san	"},
{"kanji":"鉱", "meaning": "Erz, Mineral", "reading": "	kō	"},
{"kanji":"銅", "meaning": "Kupfer", "reading": "	dō	"},
{"kanji":"像", "meaning": "Statue", "reading": "	zō	"},
{"kanji":"防", "meaning": "verhindern, verteidigen", "reading": "	bō	fuse-gu"},
{"kanji":"限", "meaning": "Grenze, einschränken", "reading": "	gen	kagi-ru"},
{"kanji":"険", "meaning": "steil", "reading": "	ken	kewa-shii"},
{"kanji":"際", "meaning": "Gelegenheit; Kante; gefährlich", "reading": "	sai	kiwa"},
{"kanji":"雑", "meaning": "Gemisch, vermischt", "reading": "	zatsu	"},
{"kanji":"非", "meaning": "un-, negativ, Fehler", "reading": "	hi	ara-zu"},
{"kanji":"修", "meaning": "sich bessern", "reading": "	shū	osa-meru"},
{"kanji":"領", "meaning": "Territorium", "reading": "	ryō	"},
{"kanji":"額", "meaning": "Stirn; Menge, Summe", "reading": "	gaku	hitai"},
{"kanji":"飼", "meaning": "(Tiere) halten, züchten", "reading": "	shi	ka-u"},
{"kanji":"士", "meaning": "Gentleman; Samurai", "reading": "	shi	"},
{"kanji":"久", "meaning": "lange Zeit", "reading": "	kyū	hisa"},
{"kanji":"仏", "meaning": "Buddha; Frankreich", "reading": "	futsu, butsu	hotoke"},
{"kanji":"仮", "meaning": "unecht; vorläufig", "reading": "	ka, ke	kari"},
{"kanji":"件", "meaning": "Angelegenheit", "reading": "	ken	"},
{"kanji":"任", "meaning": "Verantwortlichkeit, Amt", "reading": "	nin	maka-seru"},
{"kanji":"似", "meaning": "ähneln", "reading": "	ji	ni-ru"},
{"kanji":"余", "meaning": "Überschuss", "reading": "	yo	ama-ru"},
{"kanji":"価", "meaning": "Wert", "reading": "	ka	atai"},
{"kanji":"保", "meaning": "bewahren", "reading": "	ho	tamo-tsu"},
# Sechstes Schuljahr (191 kanji)
{"kanji":"党", "meaning": "politische Partei", "reading": "	tō	"},
{"kanji":"冊", "meaning": "Buch, Band", "reading": "	satsu	"},
{"kanji":"処", "meaning": "behandeln; bestrafen", "reading": "	sho	"},
{"kanji":"刻", "meaning": "schnitzen, gravieren", "reading": "	koku	kiza-mu"},
{"kanji":"割", "meaning": "aufteilen", "reading": "	katsu	wa-ru"},
{"kanji":"創", "meaning": "erschaffen", "reading": "	sō	tsuku-ru"},
{"kanji":"劇", "meaning": "Theaterstück", "reading": "	geki	"},
{"kanji":"勤", "meaning": "gewissenhaft arbeiten", "reading": "	kin	tsuto-meru"},
{"kanji":"危", "meaning": "gefährlich", "reading": "	ki	abu-nai, aya-ui"},
{"kanji":"卵", "meaning": "Ei", "reading": "	ran	tamago"},
{"kanji":"厳", "meaning": "streng, strikt", "reading": "	gen	kibi-shii"},
{"kanji":"収", "meaning": "aufbewahren; bezahlen", "reading": "	shū	osa-meru"},
{"kanji":"后", "meaning": "Kaiserin", "reading": "	kō, gō	kisaki"},
{"kanji":"否", "meaning": "verneinen", "reading": "	hi	ina, iya"},
{"kanji":"吸", "meaning": "saugen, einatmen", "reading": "	kyū	su-u"},
{"kanji":"呼", "meaning": "rufen, nennen", "reading": "	ko	yo-bu"},
{"kanji":"善", "meaning": "tugendhaft, gut", "reading": "	zen	yo-i"},
{"kanji":"困", "meaning": "in Schwierigkeiten sein", "reading": "	kon	koma-ru"},
{"kanji":"垂", "meaning": "herabhängen", "reading": "	sui	ta-reru"},
{"kanji":"優", "meaning": "sanft; überlegen sein", "reading": "	yū	yasa-shii"},
{"kanji":"域", "meaning": "Ausmaß; Region", "reading": "	iki	"},
{"kanji":"奏", "meaning": "(ein Instrument) spielen", "reading": "	sō	kana-deru"},
{"kanji":"奮", "meaning": "aufgewühlt sein, sich anstrengen", "reading": "	fun	furu-u"},
{"kanji":"姿", "meaning": "Aussehen, Gestalt", "reading": "	shi	sugata"},
{"kanji":"存", "meaning": "existieren; vermuten", "reading": "	son	"},
{"kanji":"孝", "meaning": "Respekt gegenüber den Eltern", "reading": "	kō	"},
{"kanji":"宅", "meaning": "Haus, Wohnung", "reading": "	taku	"},
{"kanji":"宇", "meaning": "Dach", "reading": "	u	"},
{"kanji":"宗", "meaning": "Religion", "reading": "	shū, sō	"},
{"kanji":"宙", "meaning": "Luft, Raum", "reading": "	chū	"},
{"kanji":"宝", "meaning": "Schatz", "reading": "	hō	takara"},
{"kanji":"宣", "meaning": "verkünden", "reading": "	sen	notama-u"},
{"kanji":"密", "meaning": "heimlich; dicht", "reading": "	mitsu	"},
{"kanji":"寸", "meaning": "Maß", "reading": "	sun	"},
{"kanji":"専", "meaning": "hauptsächlich; speziell", "reading": "	sen	moppa-ra"},
{"kanji":"射", "meaning": "schießen", "reading": "	sha	i-ru"},
{"kanji":"将", "meaning": "Anführer", "reading": "	shō	"},
{"kanji":"尊", "meaning": "achten", "reading": "	son	touto-bu"},
{"kanji":"就", "meaning": "betreffend", "reading": "	shū	tsu-ku"},
{"kanji":"尺", "meaning": "Längenmaß", "reading": "	shaku	"},
{"kanji":"届", "meaning": "senden", "reading": "	kai	todo-ku"},
{"kanji":"展", "meaning": "ausdehnen", "reading": "	ten	"},
{"kanji":"層", "meaning": "Schicht, Formation", "reading": "	sō	"},
{"kanji":"己", "meaning": "selbst", "reading": "	ko	onore"},
{"kanji":"巻", "meaning": "Buch, Rolle", "reading": "	kan	ma-ku"},
{"kanji":"幕", "meaning": "Vorhang", "reading": "	maku, baku	"},
{"kanji":"干", "meaning": "trocknen", "reading": "	kan	ho-su"},
{"kanji":"幼", "meaning": "Kindheit; kindisch", "reading": "	yō	osana-i"},
{"kanji":"庁", "meaning": "(Regierungs)behörde", "reading": "	chō	"},
{"kanji":"座", "meaning": "sitzen", "reading": "	za	suwa-ru"},
{"kanji":"延", "meaning": "verlängern", "reading": "	en	no-basu"},
{"kanji":"律", "meaning": "Rhythmus; Rechtswesen", "reading": "	ritsu	"},
{"kanji":"従", "meaning": "befolgen; unterwerfen", "reading": "	jū	shitaga-u"},
{"kanji":"忘", "meaning": "vergessen", "reading": "	bō	wasu-reru"},
{"kanji":"忠", "meaning": "Loyalität", "reading": "	chū	"},
{"kanji":"憲", "meaning": "Gesetz, Verfassung", "reading": "	ken	"},
{"kanji":"我", "meaning": "das", "reading": " Ich	ga	ware"},
{"kanji":"批", "meaning": "Kritik", "reading": "	hi	"},
{"kanji":"担", "meaning": "schultern, tragen	", "reading": "tan	nina-u"},
{"kanji":"拝", "meaning": "Verehrung", "reading": "	hai	oga-mu"},
{"kanji":"拡", "meaning": "ausbreiten", "reading": "	kaku	hiro-geru"},
{"kanji":"捨", "meaning": "aufgeben, verlassen", "reading": "	sha	su-teru"},
{"kanji":"探", "meaning": "suchen, herumtasten", "reading": "	tan	saga-su"},
{"kanji":"推", "meaning": "schlussfolgern", "reading": "	sui	"},
{"kanji":"揮", "meaning": "schwingen", "reading": "	ki	"},
{"kanji":"操", "meaning": "bedienen, steuern", "reading": "	sō	ayatsu-ru"},
{"kanji":"敬", "meaning": "Respekt", "reading": "	kei	uyama-u"},
{"kanji":"映", "meaning": "fotografieren; reflektieren	", "reading": "ei	utsu-ru"},
{"kanji":"晩", "meaning": "Abend, Nacht", "reading": "	ban	"},
{"kanji":"暖", "meaning": "warm", "reading": "	dan	atata-kai"},
{"kanji":"暮", "meaning": "Leben", "reading": "	bo	ku-rasu"},
{"kanji":"朗", "meaning": "klar, heiter, melodisch", "reading": "	rō	hoga-raka"},
{"kanji":"机", "meaning": "(Schreib)tisch", "reading": "	ki	tsukue"},
{"kanji":"枚", "meaning": "(Zählwort für flache Objekte)", "reading": "	mai	"},
{"kanji":"染", "meaning": "färben", "reading": "	sen	so-meru"},
{"kanji":"株", "meaning": "Aktie; Baumstumpf", "reading": "	shu	kabu"},
{"kanji":"棒", "meaning": "Stab, Stock", "reading": "	bō	"},
{"kanji":"模", "meaning": "imitieren", "reading": "	mo, bo	"},
{"kanji":"権", "meaning": "Autorität, Recht", "reading": "	ken	"},
{"kanji":"樹", "meaning": "Baum, Strauch	", "reading": "ju	ki"},
{"kanji":"欲", "meaning": "wünschen, haben wollen", "reading": "	yoku	ho-shii"},
{"kanji":"段", "meaning": "Stufe, Treppe", "reading": "	dan	"},
{"kanji":"沿", "meaning": "entlang verlaufen", "reading": "	en	so-u"},
{"kanji":"泉", "meaning": "Quelle", "reading": "	sen	izumi"},
{"kanji":"洗", "meaning": "waschen", "reading": "	sen	ara-u"},
{"kanji":"派", "meaning": "Gruppe, Sekte", "reading": "	ha	"},
{"kanji":"済", "meaning": "beenden", "reading": "	sai	su-mu"},
{"kanji":"源", "meaning": "Ursprung", "reading": "	gen	minamoto"},
{"kanji":"潮", "meaning": "Gezeiten", "reading": "	chō	shio"},
{"kanji":"激", "meaning": "heftig, wild", "reading": "	geki	hage-shii"},
{"kanji":"灰", "meaning": "Asche", "reading": "	kai	hai"},
{"kanji":"熟", "meaning": "reifen", "reading": "	juku	u-reru"},
{"kanji":"片", "meaning": "eine Seite (von zwei)", "reading": "	hen	kata"},
{"kanji":"班", "meaning": "Truppe", "reading": "	han	"},
{"kanji":"異", "meaning": "ungewöhnlich, verschieden", "reading": "	i	koto-naru"},
{"kanji":"疑", "meaning": "zweifeln", "reading": "	gi	utaga-u"},
{"kanji":"痛", "meaning": "Schmerz", "reading": "	tsū	ita-i"},
{"kanji":"皇", "meaning": "Kaiser", "reading": "	kō, ō	"},
{"kanji":"盛", "meaning": "gedeihend", "reading": "	sei	mo-ru"},
{"kanji":"盟", "meaning": "Bündnis", "reading": "	mei	"},
{"kanji":"看", "meaning": "beobachten", "reading": "	kan	"},
{"kanji":"砂", "meaning": "Sand", "reading": "	sa, sha	suna"},
{"kanji":"磁", "meaning": "Magnet", "reading": "	ji	"},
{"kanji":"私", "meaning": "ich; privat", "reading": "	shi	watakushi, watashi"},
{"kanji":"秘", "meaning": "Geheimnis", "reading": "	hi	hi-meru"},
{"kanji":"穀", "meaning": "Getreide", "reading": "	koku	"},
{"kanji":"穴", "meaning": "Loch", "reading": "	ketsu	ana"},
{"kanji":"窓", "meaning": "Fenster", "reading": "	sō	mado"},
{"kanji":"筋", "meaning": "Gerüst; Muskel", "reading": "	kin	suji"},
{"kanji":"策", "meaning": "Maßnahme; Plan", "reading": "	saku	"},
{"kanji":"簡", "meaning": "einfach, schlicht", "reading": "	kan	"},
{"kanji":"糖", "meaning": "Zucker", "reading": "	tō	"},
{"kanji":"系", "meaning": "Linie, System", "reading": "	kei	"},
{"kanji":"紅", "meaning": "Scharlachrot", "reading": "	kō	beni, kurenai"},
{"kanji":"納", "meaning": "zum Abschluss bringen", "reading": "	nō	osa-meru"},
{"kanji":"純", "meaning": "rein, echt", "reading": "	jun	"},
{"kanji":"絹", "meaning": "Seide", "reading": "	ken	kinu"},
{"kanji":"縦", "meaning": "vertikal", "reading": "	jū	tate"},
{"kanji":"縮", "meaning": "schrumpfen", "reading": "	shuku	chidi-mu"},
{"kanji":"署", "meaning": "Unterschrift; Behörde", "reading": "	sho	"},
{"kanji":"翌", "meaning": "folgend", "reading": "	yoku	"},
{"kanji":"聖", "meaning": "heilig", "reading": "	sei	"},
{"kanji":"肺", "meaning": "Lunge", "reading": "	hai	"},
{"kanji":"背", "meaning": "Rücken", "reading": "	hai	se"},
{"kanji":"胸", "meaning": "Brust", "reading": "	kyō	mune"},
{"kanji":"脳", "meaning": "Gehirn", "reading": "	nō	"},
{"kanji":"腹", "meaning": "Bauch", "reading": "	fuku	hara"},
{"kanji":"臓", "meaning": "inneres Organ", "reading": "	zō	"},
{"kanji":"臨", "meaning": "konfrontiert werden; kontrollieren", "reading": "	rin	nozo-mu"},
{"kanji":"至", "meaning": "äußerst; Höhepunkt", "reading": "	shi	ita-ru"},
{"kanji":"若", "meaning": "jung", "reading": "	jaku	waka-i"},
{"kanji":"著", "meaning": "berühmt; veröffentlichen; tragen", "reading": "	cho	arawa-su, ichijiru-shii"},
{"kanji":"蒸", "meaning": "Dampf", "reading": "	jō	mu-su"},
{"kanji":"蔵", "meaning": "Lager(haus)", "reading": "	zō	kura"},
{"kanji":"蚕", "meaning": "Seidenraupe", "reading": "	san	kaiko"},
{"kanji":"衆", "meaning": "Menschenmenge, Massen", "reading": "	shū	"},
{"kanji":"裁", "meaning": "ein Urteil fällen", "reading": "	sai	saba-ku"},
{"kanji":"装", "meaning": "Kleidung; schmücken", "reading": "	sō, shō	yosoo-u"},
{"kanji":"裏", "meaning": "Rückseite", "reading": "	ri	ura"},
{"kanji":"補", "meaning": "ergänzen", "reading": "	ho	ogina-u"},
{"kanji":"視", "meaning": "anschauen", "reading": "	shi	mi-ru"},
{"kanji":"覧", "meaning": "ansehen, betrachten", "reading": "	ran	"},
{"kanji":"討", "meaning": "strafen; angreifen", "reading": "	tō	u-tsu"},
{"kanji":"訪", "meaning": "besuchen", "reading": "	hō	otozu-reru"},
{"kanji":"訳", "meaning": "Übersetzung", "reading": "	yaku	wake"},
{"kanji":"詞", "meaning": "Worte, Dichtung", "reading": "	shi	kotoba"},
{"kanji":"誌", "meaning": "Dokument, Bericht", "reading": "	shi	"},
{"kanji":"認", "meaning": "(an)erkennen", "reading": "	nin	mito-meru"},
{"kanji":"誕", "meaning": "Geburt; Lüge", "reading": "	tan	"},
{"kanji":"誠", "meaning": "Aufrichtigkeit", "reading": "	sei	makoto"},
{"kanji":"誤", "meaning": "sich irren", "reading": "	go	ayama-ru"},
{"kanji":"論", "meaning": "Theorie, Argumentation", "reading": "	ron	"},
{"kanji":"諸", "meaning": "verschieden", "reading": "	sho	moro"},
{"kanji":"警", "meaning": "ermahnen, warnen", "reading": "	kei	imashi-meru"},
{"kanji":"貴", "meaning": "wertvoll", "reading": "	ki	tatto-i"},
{"kanji":"賃", "meaning": "Gebühr, Lohn", "reading": "	chin	"},
{"kanji":"遺", "meaning": "hinterlassen", "reading": "	i	"},
{"kanji":"郵", "meaning": "Post", "reading": "	yū	"},
{"kanji":"郷", "meaning": "Heimatort", "reading": "	kyō	gō"},
{"kanji":"針", "meaning": "Nadel, Stachel", "reading": "	shin	hari"},
{"kanji":"鋼", "meaning": "Stahl", "reading": "	kō	hagane"},
{"kanji":"閉", "meaning": "schließen", "reading": "	hei	shi-meru"},
{"kanji":"閣", "meaning": "hohes Gebäude, Palast", "reading": "	kaku	"},
{"kanji":"降", "meaning": "hinuntergehen, fallen", "reading": "	kō	o-riru"},
{"kanji":"陛", "meaning": "Majestät", "reading": "	hei	"},
{"kanji":"除", "meaning": "ausschließen", "reading": "	jo, ji	nozo-ku"},
{"kanji":"障", "meaning": "hemmen, schaden", "reading": "	shō	sawa-ru"},
{"kanji":"難", "meaning": "schwierig", "reading": "	nan	muzuka-shii"},
{"kanji":"革", "meaning": "Leder", "reading": "	kaku	kawa"},
{"kanji":"頂", "meaning": "Scheitel, auf dem Kopf tragen", "reading": "	chō	itada-ku"},
{"kanji":"骨", "meaning": "Knochen", "reading": "	kotsu	hone"},
{"kanji":"胃", "meaning": "Magen", "reading": "	i	"},
{"kanji":"腸", "meaning": "Eingeweide", "reading": "	chō	harawata"},
{"kanji":"券", "meaning": "(Eintritts/Fahr)karte", "reading": "	ken	"},
{"kanji":"承", "meaning": "erhalten; hinnehmen", "reading": "	shō	uketamawa-ru"},
{"kanji":"舌", "meaning": "Zunge", "reading": "	zetsu	shita"},
{"kanji":"銭", "meaning": "Münze, Geld	", "reading": "sen	zeni"},
{"kanji":"退", "meaning": "sich zurückziehen", "reading": "	tai	shirizo-ku"},
{"kanji":"敵", "meaning": "Feind", "reading": "	teki	kataki"},
{"kanji":"俵", "meaning": "Strohsack", "reading": "	hyō	tawara"},
{"kanji":"預", "meaning": "in Verwahrung geben/nehmen", "reading": "	yo	azu-keru"},
{"kanji":"恩", "meaning": "Gnade, Gefallen", "reading": "	on	"},
{"kanji":"並", "meaning": "Reihe, nebeneinander stehen", "reading": "	hei	nami, nara-bu"},
{"kanji":"乱", "meaning": "Unordnung, Chaos", "reading": "	ran	mida-reru"},
{"kanji":"乳", "meaning": "Milch", "reading": "	nyū	chichi"},
{"kanji":"亡", "meaning": "verstorben", "reading": "	bō	na-kunaru"},
{"kanji":"仁", "meaning": "Barmherzigkeit", "reading": "	jin	"},
{"kanji":"供", "meaning": "anbieten; Begleiter", "reading": "	kyō, ku	tomo"},
{"kanji":"俳", "meaning": "Haiku; Schauspieler", "reading": "	hai	"},
{"kanji":"値", "meaning": "Preis, Wert", "reading": "	chi	atai"},
{"kanji":"傷", "meaning": "Wunde", "reading": "	shō	kizu"}
]

# Clear font cache
font_cache_path = mpl.get_cachedir()
if font_cache_path:
    for filename in os.listdir(font_cache_path):
        if filename.startswith('fontList'):
             os.remove(os.path.join(font_cache_path, filename))


# Find the path to the font
# japanese_font_path = fm.findfont(fm.FontProperties(family='Noto Sans CJK JP'))
japanese_font_path = '/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc'
# font = ImageFont.load_default()

image_size = (190, 60)
font_size = 10
font = ImageFont.truetype(japanese_font_path, font_size)

for data in kanji_data:
    img = Image.new('RGB', image_size, color = (73, 109, 137))
    d = ImageDraw.Draw(img)
   #  kanji_width, kanji_height = d.textsize(data["kanji"], font=font)
    kanji_bbox = d.textbbox((0, 0), data["kanji"], font=font)
    kanji_width = kanji_bbox[2] - kanji_bbox[0]
    kanji_height = kanji_bbox[3] - kanji_bbox[1]
    # Draw Kanji, Meaning, Reading
    d.text((10, 10), data["kanji"], font=font, fill=(255, 255, 0))
    # d.text((10, 40), data["meaning"], font=font, fill=(255, 255, 255))
    d.text((20 + kanji_width, 10), f"- {data['meaning']}", font=font, fill=(255, 255, 255))
    d.text((10, 40), data["reading"], font=font, fill=(255, 255, 255))

    img.save(f"{data['kanji']}.png")
#    print(f"Font path: {japanese_font_path}")
#    print(f"Font file exists: {os.path.exists(japanese_font_path)}")
    print("Images created successfully!")

# image_paths = glob.glob("*.png")
image_paths = [f"{data['kanji']}.png" for data in kanji_data]
# Assuming you have a list of image paths
# image_paths = ["一.png", "二.png"]  # Add all your image paths here

# Open all images
images = [Image.open(path) for path in image_paths]

# Determine the size of the grid
num_images = len(images)
grid_size = math.ceil(math.sqrt(num_images))

# Create a new image with the appropriate size
max_width = max(img.width for img in images)
max_height = max(img.height for img in images)
padding = 10
# grid_image = Image.new('RGB', (grid_size * max_width, grid_size * max_height))
grid_image = Image.new('RGB', (grid_size * (max_width + padding), grid_size * (max_height + padding)))

# Paste the images into the grid
for index, img in enumerate(images):
    row = index // grid_size
    col = index % grid_size
    grid_image.paste(img, (col * (max_width + padding), row * (max_height + padding)))
    # grid_image.paste(img, (col * max_width, row * max_height))
    # grid_image = Image.new('RGB', (width, height), color=(240, 240, 240))

    border_width = 2
    border_color = (0, 0, 0)
    draw = ImageDraw.Draw(grid_image)
    # draw.text((col * (max_width + padding) + 10, (row + 1) * max_height + row * padding + 10), f"{data['kanji']} - {data['meaning']}", fill=(0, 0, 0))
    draw.rectangle([(col * (max_width + padding), row * (max_height + padding)),
                     ((col + 1) * max_width + col * padding - 1, (row + 1) * max_height + row * padding - 1)],
                    outline=border_color, width=border_width)

# Save the final grid image
grid_image.save("kanji_grid.png")

print("Image created successfully!")

"""nounce finder"""

import hashlib
import hmac
input_str = "12764:c31451e31a94d691027456e63e2d01e3b28053d3bdafb97fd55d2400c1842f4a:12764"
nonce = "12764"


def find_x_value(input_str, nonce):
    for x in range(256):
        secret_key = f"{nonce}:{x:02X}:{nonce}"
        hmac_sha512 = hmac.new(secret_key.encode(), input_str.encode(), hashlib.sha512)
        output = hmac_sha512.hexdigest()
        if output.startswith("ffffffff"):
            return x
    return None


x_value = find_x_value(input_str, nonce)
if x_value is not None:
    print(f"The value of X should be: {x_value:02X}")
else:
    print("No value of X found that produces the desired HMAC-SHA512 output.")

!python3 -m venv myenv
!source myenv/bin/activate
!pip install python-docx docx2pdf
from docx import Document
import csv
from docx2pdf import convert
import os

# Absoluten Pfad erstellen
# script_dir = os.path.dirname(__file__)     <-on vscode; v on jupiter
script_dir = os.getcwd()
template_path = os.path.join(script_dir, "bew_template.docx")

# Prüfen ob die Datei existiert und lesbar ist
print(f"Suche nach Vorlage in: {template_path}")
if not os.path.exists(template_path):
    print("FEHLER: Datei wurde nicht gefunden!")
    exit()

# Prüfe Dateigröße und Berechtigungen
file_size = os.path.getsize(template_path)
print(f"Dateigröße: {file_size} Bytes")
print(f"Dateiberechtigungen: {oct(os.stat(template_path).st_mode & 0o777)}")

# Ausgabeverzeichnis erstellen
output_folder = os.path.join(script_dir, "bewerbungen")
os.makedirs(output_folder, exist_ok=True)
print(f"Ausgabeordner erstellt: {output_folder}")

try:
    # CSV-Datei mit Adressen öffnen
    with open("adressen.csv", newline="", encoding="utf-8") as csvfile:
        reader = csv.DictReader(csvfile, fieldnames=["Name", "Adresse", "Stadt"])

        # Überspringe Header (falls vorhanden)
        next(reader)

        for row in reader:
            print(f"\nVerarbeite Eintrag für {row['Name']}")

            try:
                # Versuche die Datei zu öffnen
                print(f"Versuche Vorlage zu laden: {template_path}")
                doc = Document(template_path)

                # Platzhalter ersetzen
                for paragraph in doc.paragraphs:
                    if "{{Name}}" in paragraph.text:
                        paragraph.text = paragraph.text.replace("{{Name}}", row["Name"])
                    if "{{Adresse}}" in paragraph.text:
                        paragraph.text = paragraph.text.replace(
                            "{{Adresse}}", row["Adresse"]
                        )
                    if "{{Stadt}}" in paragraph.text:
                        paragraph.text = paragraph.text.replace(
                            "{{Stadt}}", row["Stadt"]
                        )

                # Speichern als Word-Dokument
                output_path = os.path.join(
                    output_folder, f"bewerbung_{row['Name']}.docx"
                )
                doc.save(output_path)
                print(f"Dokument gespeichert: {output_path}")

            except Exception as e:
                print(f"Fehler beim Verarbeiten von {row['Name']}: {str(e)}")
                continue

    convert(output_folder, output_folder)
    print("\nAlle Dokumente wurden erfolgreich konvertiert!")

except Exception as e:
    print(f"\nEin unerwarteter Fehler ist aufgetreten: {str(e)}")
    print(f"Arbeitsverzeichnis: {os.getcwd()}")
    print(f"Pfad der ausführenden Datei: {script_dir}")
    print(f"Betriebssystem: {os.name}")

from PIL import Image, ImageDraw, ImageFont

# Create a blank image
width, height = 600, 300
image = Image.new("RGB", (width, height), "white")
draw = ImageDraw.Draw(image)

# Draw breadboard power rails
draw.rectangle([50, 20, 550, 40], fill="#FFCCCC")  # Positive rail
draw.text((10, 25), "+", fill="red")
draw.rectangle([50, 260, 550, 280], fill="#CCCCFF")  # Negative rail
draw.text((10, 265), "-", fill="blue")

# Draw columns (simplified)
for i in range(20):
    x = 50 + i * 25
    draw.line((x, 60, x, 240), fill="lightgray")

# Draw center gap
draw.rectangle([290, 60, 310, 240], fill="white")

# Draw LED (anode to cathode)
draw.ellipse([225, 100, 235, 110], fill="red")  # Anode
draw.text((240, 95), "LED", fill="black")
draw.line((230, 105, 230, 145), fill="black", width=2)  # To resistor

# Draw resistor
draw.rectangle([225, 145, 235, 155], fill="orange")
draw.text((190, 150), "220Ω", fill="black")

# Resistor to negative rail
draw.line((230, 155, 230, 260), fill="black", width=2)

# Jumper from power rail to LED anode
draw.line((100, 20, 100, 100), fill="red", width=2)
draw.line((100, 100, 225, 100), fill="red", width=2)

# Legend
draw.text((400, 50), "Red: Power (+)", fill="red")
draw.text((400, 70), "Blue: Ground (–)", fill="blue")
draw.text((400, 90), "Black: Signal path", fill="black")
draw.text((400, 110), "Orange: Resistor", fill="orange")

image.save("led_breadboard_diagram.png")
image.show()